"use client"

import { useMemo, useState } from "react"
import { Archive, BarChart3, CircleDollarSign, Megaphone, MousePointerClick, Pencil, Plus, UsersRound } from "lucide-react"
import { toast } from "sonner"

import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { campaignAdapters, campaignChannels, calculateCampaignMetrics, type CampaignChannel, type CommercialCampaign } from "@/features/commercial/commercial-campaigns"
import { useAuthorizedCommercial } from "@/features/identity/use-authorized-commercial"

const euro = new Intl.NumberFormat("it-IT", { style: "currency", currency: "EUR", maximumFractionDigits: 0 })
const number = new Intl.NumberFormat("it-IT", { maximumFractionDigits: 1 })
type Form = { name: string; channel: CampaignChannel; account: string; status: CommercialCampaign["status"]; startsAt: string; endsAt: string; spend: string; impressions: string; clicks: string }
const emptyForm = (): Form => ({ name: "", channel: "Meta Ads", account: "", status: "draft", startsAt: new Date().toISOString().slice(0, 10), endsAt: "", spend: "0", impressions: "0", clicks: "0" })

function Kpi({ label, value, icon: Icon, active, onClick }: { label: string; value: string; icon: typeof Megaphone; active?: boolean; onClick?: () => void }) {
  return <button type="button" aria-pressed={active} onClick={onClick} className={`rounded-xl border bg-card p-4 text-left shadow-sm transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring ${active ? "border-primary bg-primary/5" : "hover:bg-muted/40"}`}><span className="flex items-center justify-between gap-2 text-xs font-medium text-muted-foreground">{label}<Icon className="size-4" /></span><strong className="mt-2 block text-2xl tabular-nums">{value}</strong></button>
}

export function CommercialCampaignsPage() {
  const { store, leads, identity } = useAuthorizedCommercial()
  const admin = identity.currentUser.roles.includes("administrator")
  const [query, setQuery] = useState(""); const [channel, setChannel] = useState("all"); const [selectedId, setSelectedId] = useState<string>(); const [metricFilter, setMetricFilter] = useState<"all" | "active" | "paying">("all")
  const [dialogOpen, setDialogOpen] = useState(false); const [editingId, setEditingId] = useState<string>(); const [form, setForm] = useState<Form>(emptyForm)
  const signed = useMemo(() => new Set(store.contracts.filter((contract) => contract.status === "Firmato" && !contract.archivedAt && !contract.replacedById).map((contract) => contract.orderId)), [store.contracts])
  const rows = useMemo(() => store.campaigns.map((campaign) => ({ campaign, metrics: calculateCampaignMetrics(campaign, leads, store.sales, store.orders, store.payments, signed) })).filter(({ campaign, metrics }) => (channel === "all" || campaign.channel === channel) && (!query || `${campaign.name} ${campaign.account}`.toLocaleLowerCase("it-IT").includes(query.toLocaleLowerCase("it-IT"))) && (metricFilter === "all" || metricFilter === "active" && campaign.status === "active" || metricFilter === "paying" && metrics.payingCustomers > 0)), [channel, leads, metricFilter, query, signed, store.campaigns, store.orders, store.payments, store.sales])
  const totals = useMemo(() => rows.reduce((sum, row) => ({ spend: sum.spend + row.metrics.spend, clicks: sum.clicks + row.metrics.clicks, leads: sum.leads + row.metrics.leads, paying: sum.paying + row.metrics.payingCustomers, net: sum.net + row.metrics.netCollected }), { spend: 0, clicks: 0, leads: 0, paying: 0, net: 0 }), [rows])
  const selected = rows.find((row) => row.campaign.id === selectedId) ?? rows[0]
  const openCreate = () => { setEditingId(undefined); setForm(emptyForm()); setDialogOpen(true) }
  const openEdit = (campaign: CommercialCampaign) => { setEditingId(campaign.id); setForm({ name: campaign.name, channel: campaign.channel, account: campaign.account, status: campaign.status, startsAt: campaign.startsAt, endsAt: campaign.endsAt ?? "", spend: String(campaign.spend), impressions: String(campaign.impressions), clicks: String(campaign.clicks) }); setDialogOpen(true) }
  const save = () => { const spend = Number(form.spend); const impressions = Number(form.impressions); const clicks = Number(form.clicks); if (!form.name.trim() || !form.account.trim() || [spend, impressions, clicks].some((value) => !Number.isFinite(value) || value < 0) || clicks > impressions) { toast.error("Controlla nome, account e metriche della campagna."); return } const payload = { name: form.name, channel: form.channel, account: form.account, status: form.status, startsAt: form.startsAt, endsAt: form.endsAt || undefined, spend, impressions, clicks, adGroups: [] }; const ok = editingId ? store.updateCampaign(editingId, payload) : Boolean(store.addCampaign(payload)); if (!ok) { toast.error("Campagna non salvata."); return } toast.success(editingId ? "Campagna aggiornata" : "Campagna creata"); setDialogOpen(false) }
  return <main className="mx-auto w-full max-w-7xl space-y-6 p-4 md:p-6">
    <header className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-medium uppercase tracking-wider text-muted-foreground">Acquisizione reale</p><h1 className="text-2xl font-semibold">Campagne e qualità dei lead</h1><p className="mt-1 text-sm text-muted-foreground">Dal canale all’incasso netto: “Vinto” non equivale a cliente pagante.</p></div>{admin && <Button onClick={openCreate}><Plus />Nuova campagna</Button>}</header>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Kpi label="Spesa" value={euro.format(totals.spend)} icon={CircleDollarSign} /><Kpi label="Click" value={number.format(totals.clicks)} icon={MousePointerClick} /><Kpi label="Lead attribuiti" value={number.format(totals.leads)} icon={UsersRound} active={metricFilter === "active"} onClick={() => setMetricFilter(metricFilter === "active" ? "all" : "active")} /><Kpi label="Clienti paganti" value={number.format(totals.paying)} icon={UsersRound} active={metricFilter === "paying"} onClick={() => setMetricFilter(metricFilter === "paying" ? "all" : "paying")} /><Kpi label="Incassato netto" value={euro.format(totals.net)} icon={BarChart3} /></section>
    <Card><CardHeader><CardTitle>Confronto campagne</CardTitle><CardDescription>Metriche derivate da attribuzioni, ordini, contratti, pagamenti e rimborsi persistenti.</CardDescription><div className="grid gap-2 pt-2 sm:grid-cols-[minmax(0,1fr)_220px_auto]"><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Cerca campagna o account…" aria-label="Cerca campagne" /><Select value={channel} onValueChange={setChannel}><SelectTrigger aria-label="Filtra canale"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">Tutti i canali</SelectItem>{campaignChannels.map((item) => <SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent></Select><Button variant="outline" onClick={() => { setQuery(""); setChannel("all"); setMetricFilter("all") }}>Azzera filtri</Button></div></CardHeader><CardContent className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Campagna</TableHead><TableHead>Lead</TableHead><TableHead>Qualificati</TableHead><TableHead>Paganti</TableHead><TableHead>CTR</TableHead><TableHead>CPL</TableHead><TableHead>CAC</TableHead><TableHead>ROAS netto</TableHead><TableHead className="text-right">Azioni</TableHead></TableRow></TableHeader><TableBody>{rows.map(({ campaign, metrics }) => <TableRow key={campaign.id} className="cursor-pointer" onClick={() => setSelectedId(campaign.id)}><TableCell><span className="font-medium">{campaign.name}</span><span className="block text-xs text-muted-foreground">{campaign.channel} · {campaign.account}</span></TableCell><TableCell>{metrics.leads}</TableCell><TableCell>{metrics.qualifiedLeads}</TableCell><TableCell>{metrics.payingCustomers}</TableCell><TableCell>{number.format(metrics.ctr)}%</TableCell><TableCell>{euro.format(metrics.leads ? metrics.spend / metrics.leads : 0)}</TableCell><TableCell>{euro.format(metrics.cac)}</TableCell><TableCell>{number.format(metrics.netRoas)}×</TableCell><TableCell className="text-right">{admin && <span className="inline-flex gap-1"><Button size="icon-sm" variant="ghost" aria-label={`Modifica ${campaign.name}`} onClick={(event) => { event.stopPropagation(); openEdit(campaign) }}><Pencil /></Button><Button size="icon-sm" variant="ghost" aria-label={`Archivia ${campaign.name}`} onClick={(event) => { event.stopPropagation(); if (store.archiveCampaign(campaign.id)) toast.success("Campagna archiviata") }}><Archive /></Button></span>}</TableCell></TableRow>)}{!rows.length && <TableRow><TableCell colSpan={9} className="h-28 text-center text-muted-foreground">Nessuna campagna reale nel perimetro selezionato.</TableCell></TableRow>}</TableBody></Table></CardContent></Card>
    {selected && <Card><CardHeader><CardTitle>Drill-down · {selected.campaign.name}</CardTitle><CardDescription>Qualità fonte {selected.metrics.sourceQuality}/100 · chiusura media {number.format(selected.metrics.averageCloseDays)} giorni.</CardDescription></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div><span className="text-xs text-muted-foreground">Proposte</span><strong className="block text-xl">{selected.metrics.proposals}</strong></div><div><span className="text-xs text-muted-foreground">Contratti firmati</span><strong className="block text-xl">{selected.metrics.signedContracts}</strong></div><div><span className="text-xs text-muted-foreground">Venduto / fatturato</span><strong className="block text-xl">{euro.format(selected.metrics.sold)} / {euro.format(selected.metrics.invoiced)}</strong></div><div><span className="text-xs text-muted-foreground">Lordo / rimborsato</span><strong className="block text-xl">{euro.format(selected.metrics.grossCollected)} / {euro.format(selected.metrics.refunded)}</strong></div><div className="sm:col-span-2 lg:col-span-4"><span className="text-xs text-muted-foreground">Lead attribuiti</span><div className="mt-2 flex flex-wrap gap-2">{leads.filter((lead) => lead.campaignId === selected.campaign.id).map((lead) => <Badge key={lead.id} variant="secondary">{lead.company}</Badge>)}{!leads.some((lead) => lead.campaignId === selected.campaign.id) && <span className="text-sm text-muted-foreground">Nessun lead attribuito.</span>}</div></div></CardContent></Card>}
    <Card><CardHeader><CardTitle>Adattatori pubblicitari</CardTitle><CardDescription>Predisposizione esplicita: nessuna chiamata esterna o credenziale nel frontend.</CardDescription></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2">{campaignAdapters.map((adapter) => <div key={adapter.provider} className="rounded-lg border p-3"><div className="flex items-center justify-between gap-2"><span className="font-medium">{adapter.provider}</span><Badge variant="outline">Disabilitato</Badge></div><p className="mt-1 text-xs text-muted-foreground">{adapter.reason}</p></div>)}</CardContent></Card>
    <Dialog open={dialogOpen} onOpenChange={setDialogOpen}><DialogContent className="max-h-[calc(100dvh-2rem)] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>{editingId ? "Modifica campagna" : "Nuova campagna"}</DialogTitle><DialogDescription>I valori sono manuali e persistenti; non vengono importati da piattaforme esterne.</DialogDescription></DialogHeader><div className="grid gap-3 sm:grid-cols-2"><div className="space-y-1.5"><Label htmlFor="campaign-name">Nome</Label><Input id="campaign-name" value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></div><div className="space-y-1.5"><Label htmlFor="campaign-account">Account</Label><Input id="campaign-account" value={form.account} onChange={(event) => setForm({ ...form, account: event.target.value })} /></div><div className="space-y-1.5"><Label>Canale</Label><Select value={form.channel} onValueChange={(value) => setForm({ ...form, channel: value as CampaignChannel })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{campaignChannels.map((item) => <SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent></Select></div><div className="space-y-1.5"><Label>Stato</Label><Select value={form.status} onValueChange={(value) => setForm({ ...form, status: value as CommercialCampaign["status"] })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{["draft", "active", "paused", "completed"].map((item) => <SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent></Select></div>{(["startsAt", "endsAt", "spend", "impressions", "clicks"] as const).map((field) => <div key={field} className="space-y-1.5"><Label htmlFor={`campaign-${field}`}>{field === "startsAt" ? "Inizio" : field === "endsAt" ? "Fine" : field === "spend" ? "Spesa" : field === "impressions" ? "Impression" : "Click"}</Label><Input id={`campaign-${field}`} type={field === "startsAt" || field === "endsAt" ? "date" : "number"} min={field === "startsAt" || field === "endsAt" ? undefined : 0} value={form[field]} onChange={(event) => setForm({ ...form, [field]: event.target.value })} /></div>)}</div><DialogFooter><Button variant="outline" onClick={() => setDialogOpen(false)}>Annulla</Button><Button onClick={save}>Salva campagna</Button></DialogFooter></DialogContent></Dialog>
  </main>
}
