"use client"

import Link from "next/link"
import { usePathname, useRouter, useSearchParams } from "next/navigation"
import { DndContext, KeyboardSensor, PointerSensor, TouchSensor, closestCorners, useDraggable, useDroppable, useSensor, useSensors, type DragEndEvent } from "@dnd-kit/core"
import { CSS } from "@dnd-kit/utilities"
import { CalendarClock, FolderKanban, GripVertical, List, Rows3, Timer, Users } from "lucide-react"

import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { getCanonicalCustomerActivities, type CommercialCustomer, type CommercialProject } from "@/features/commercial/components/commercial-leads-provider"
import { CustomerLogo } from "@/features/commercial/components/customer-logo"
import { RankingWinnerBadges } from "@/features/commercial/components/ranking-winner-badges"
import { RecordCollaborationPanel } from "@/features/commercial/components/record-collaboration-panel"
import { TeamWorkloadView } from "@/features/commercial/components/team-workload-view"
import { getProjectDisplayProgress, getProjectStatusVisual, projectProgress, projectStatuses } from "@/features/commercial/commercial-production"
import { ProjectStatusBadge } from "@/features/commercial/components/project-status-badge"
import { AccessDenied } from "@/features/identity/access-denied"
import { canManageProject } from "@/features/identity/permissions"
import { useAuthorizedCommercial } from "@/features/identity/use-authorized-commercial"
import { formatItalianDate } from "@/lib/date"

export function CommercialProjectsPage() {
  const router = useRouter(); const pathname = usePathname(); const searchParams = useSearchParams()
  const authorized = useAuthorizedCommercial(); const { store, identity, projects, customers } = authorized
  const sensors = useSensors(useSensor(PointerSensor, { activationConstraint: { distance: 6 } }), useSensor(TouchSensor, { activationConstraint: { delay: 180, tolerance: 8 } }), useSensor(KeyboardSensor))
  if (!identity.hasCapability("canViewProjects")) return <AccessDenied resource="ai progetti" />
  const mineOnly = searchParams.get("scope") === "mine"
  const activeProjects = projects.filter((project) => !project.archivedAt && (!mineOnly || project.ownerId === identity.currentUserId || project.memberIds.includes(identity.currentUserId)))
  const activities = authorized.activities.map(({ activity }) => activity).filter((activity) => !activity.archivedAt && activeProjects.some((project) => project.id === activity.projectId))
  const move = ({ active, over }: DragEndEvent) => { if (!over) return; const project = activeProjects.find((item) => item.id === active.id); const status = String(over.id).replace("status:", "") as CommercialProject["status"]; if (project && projectStatuses.includes(status) && project.status !== status && canManageProject(identity.currentUser, project)) store.updateProject(project.id, { status }) }
  const deadlines = [...activities].filter((activity) => activity.status !== "Completata" && activity.status !== "Annullata").sort((a, b) => a.dueAt.localeCompare(b.dueAt))
  const events = store.timelineEvents.filter((event) => activeProjects.some((project) => (project.sourceLeadId ?? project.clientId) === event.leadId)).sort((a, b) => b.date.localeCompare(a.date))

  return <main data-flow-tour="flow-projects" className="mx-auto w-full max-w-[1600px] space-y-5 p-4 md:p-6"><header data-flow-tour="flow-projects-header" className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-2xl font-semibold">Progetti e Produzione</h1><p className="text-sm text-muted-foreground">Pianificazione, avanzamento ponderato, scadenze, Timeline e carico autorizzato.</p></div><div className="flex flex-wrap items-center gap-2">{mineOnly && <Badge variant="secondary">Assegnati a me / in team</Badge>}<Badge variant="outline">{activeProjects.length} progetti</Badge>{mineOnly && <Button size="sm" variant="ghost" onClick={() => router.replace(pathname)}>Azzera filtri</Button>}</div></header><Tabs defaultValue="list"><div className="overflow-x-auto"><TabsList className="min-w-max"><TabsTrigger value="list"><List />Lista</TabsTrigger><TabsTrigger value="kanban"><Rows3 />Kanban</TabsTrigger><TabsTrigger value="deadlines"><CalendarClock />Scadenze</TabsTrigger><TabsTrigger value="timeline"><Timer />Timeline</TabsTrigger><TabsTrigger value="workload"><Users />Carico</TabsTrigger></TabsList></div>
    <TabsContent value="list"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{activeProjects.map((project,index) => <ProjectCard key={project.id} project={project} customer={customers.find((item) => item.id === project.clientId)} activities={activities.filter((item) => item.projectId === project.id)} canManage={canManageProject(identity.currentUser, project)} onStatus={(status) => store.updateProject(project.id, { status })} owner={identity.users.find((item) => item.id === project.ownerId)?.name} tourTarget={index===0} />)}</div>{!activeProjects.length && <Empty />}</TabsContent>
    <TabsContent value="kanban"><DndContext sensors={sensors} collisionDetection={closestCorners} onDragEnd={move}><div className="grid min-w-0 grid-cols-1 items-start gap-3 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{projectStatuses.map((status) => <StatusColumn key={status} status={status} projects={activeProjects.filter((project) => project.status === status)} canMove={(project) => canManageProject(identity.currentUser, project)} />)}</div></DndContext></TabsContent>
    <TabsContent value="deadlines"><Card><CardHeader><CardTitle>Scadenze di produzione</CardTitle><CardDescription>Attività aperte in ordine cronologico.</CardDescription></CardHeader><CardContent className="space-y-2">{deadlines.map((activity) => { const project = activeProjects.find((item) => item.id === activity.projectId); return <Link key={activity.id} href={`/dashboard/progetti/${activity.projectId}?tab=activities`} className="flex flex-wrap items-center gap-2 rounded-lg border p-3 hover:bg-muted"><span className="min-w-0 flex-1 font-medium">{activity.title}</span>{project && <ProjectStatusBadge status={project.status} />}<Badge variant="secondary">{activity.status}</Badge><span className="text-sm text-muted-foreground">{formatItalianDate(activity.dueAt)}</span></Link> })}{!deadlines.length && <p className="text-sm text-muted-foreground">Nessuna scadenza aperta.</p>}</CardContent></Card></TabsContent>
    <TabsContent value="timeline"><Card><CardHeader><CardTitle>Timeline produzione</CardTitle></CardHeader><CardContent className="space-y-3">{events.slice(0, 100).map((event) => { const project = activeProjects.find((item) => (item.sourceLeadId ?? item.clientId) === event.leadId); return <div key={event.id} className="border-l-2 pl-3"><div className="flex flex-wrap items-center gap-2"><p className="font-medium">{event.title}</p>{project && <ProjectStatusBadge status={project.status} />}</div><p className="text-sm text-muted-foreground">{event.detail} · {new Date(event.date).toLocaleString("it-IT")}</p></div> })}{!events.length && <p className="text-sm text-muted-foreground">Nessun evento di produzione.</p>}</CardContent></Card></TabsContent>
    <TabsContent value="workload"><TeamWorkloadView /></TabsContent>
  </Tabs></main>
}

function ProjectCard({ project, customer, activities, canManage, onStatus, owner, tourTarget=false }: { project: CommercialProject; customer?: CommercialCustomer; activities: ReturnType<typeof getCanonicalCustomerActivities>; canManage: boolean; onStatus: (status: CommercialProject["status"]) => void; owner?: string; tourTarget?: boolean }) {
  const progress = projectProgress(project, activities); const displayProgress = getProjectDisplayProgress(project, progress.internal); const visual = getProjectStatusVisual(project.status); const StatusIcon = visual.icon
  return <Card><CardHeader><div className="flex items-start justify-between gap-2"><FolderKanban className="size-5 text-muted-foreground" /><div data-flow-tour={tourTarget ? "flow-project-delivery" : undefined} className="flex items-center gap-1"><RecordCollaborationPanel recordType="project" recordId={project.id} label={project.name} triggerVariant="list" /><ProjectStatusBadge status={project.status} /></div></div><div className="flex items-center gap-2">{customer && <CustomerLogo customer={customer} className="size-9" />}<div className="min-w-0"><CardTitle className="truncate text-base">{project.name}</CardTitle><CardDescription className="truncate">{customer?.profile.company ?? "Cliente autorizzato"} · {project.service}</CardDescription></div></div></CardHeader><CardContent className="space-y-3 text-sm"><div data-flow-tour={tourTarget ? "flow-project-team" : undefined} className="flex flex-wrap items-center gap-1"><span className="text-muted-foreground">Responsabile: {owner ?? project.ownerId}</span><RankingWinnerBadges userId={project.ownerId} compact /></div><div><div className="flex justify-between"><span>Avanzamento ponderato</span><strong>{displayProgress}%</strong></div><div className="mt-1 h-2 rounded-full bg-muted"><div className={`h-full rounded-full ${visual.progressClass}`} style={{ width: `${displayProgress}%` }} /></div></div><p className="text-muted-foreground">Scadenza: {project.dueDate ? formatItalianDate(project.dueDate) : "Non definita"}</p>{canManage && <Select value={project.status} onValueChange={(status) => onStatus(status as CommercialProject["status"])}><SelectTrigger data-flow-tour={tourTarget ? "flow-project-phases" : undefined} aria-label={`Stato ${project.name}`} className={visual.badgeClass}><span className="flex min-w-0 items-center gap-2"><StatusIcon className="size-4 shrink-0" /><SelectValue /></span></SelectTrigger><SelectContent>{projectStatuses.map((status) => { const option = getProjectStatusVisual(status); const Icon = option.icon; return <SelectItem key={status} value={status}><span className="flex items-center gap-2"><Icon className="size-4" />{option.label}</span></SelectItem> })}</SelectContent></Select>}<Button asChild className="w-full"><Link href={`/dashboard/progetti/${project.id}`}>Apri progetto</Link></Button></CardContent></Card>
}
function StatusColumn({ status, projects, canMove }: { status: CommercialProject["status"]; projects: CommercialProject[]; canMove: (project: CommercialProject) => boolean }) { const { setNodeRef, isOver } = useDroppable({ id: `status:${status}` }); const visual = getProjectStatusVisual(status); const Icon = visual.icon; return <section ref={setNodeRef} className={`min-w-0 rounded-xl border p-3 ${visual.columnClass} ${isOver ? "ring-2 ring-primary/50" : ""}`}><header className="mb-3 flex min-w-0 items-center justify-between gap-2"><h2 className="flex min-w-0 items-center gap-2 font-medium"><Icon className="size-4 shrink-0" /><span className="truncate" title={visual.label}>{visual.label}</span></h2><Badge variant="secondary" className="shrink-0">{projects.length}</Badge></header><div className="min-h-16 space-y-2">{projects.map((project) => <DraggableProject key={project.id} project={project} disabled={!canMove(project)} />)}{!projects.length && <p className="rounded-lg border border-dashed p-4 text-center text-xs text-muted-foreground">Trascina qui</p>}</div></section> }
function DraggableProject({ project, disabled }: { project: CommercialProject; disabled: boolean }) { const { setNodeRef, transform, isDragging, listeners, attributes } = useDraggable({ id: project.id, disabled }); return <Card ref={setNodeRef} style={{ transform: CSS.Translate.toString(transform), opacity: isDragging ? .45 : 1 }}><CardContent className="flex items-start gap-2 p-3"><button {...listeners} {...attributes} disabled={disabled} aria-label={`Sposta ${project.name}`} className="mt-0.5 cursor-grab disabled:cursor-not-allowed"><GripVertical className="size-4 text-muted-foreground" /></button><Link className="min-w-0 flex-1" href={`/dashboard/progetti/${project.id}`}><p className="truncate font-medium">{project.name}</p><p className="truncate text-xs text-muted-foreground">{project.service}</p><ProjectStatusBadge status={project.status} className="mt-2" /></Link></CardContent></Card> }
function Empty() { return <Card><CardHeader><CardTitle>Nessun progetto assegnato</CardTitle><CardDescription>Il perimetro corrente non contiene progetti visibili.</CardDescription></CardHeader></Card> }
