"use client"

import Link from "next/link"
import { useState } from "react"
import { AlertTriangle, X } from "lucide-react"
import { toast } from "sonner"
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog"
import { Button } from "@/components/ui/button"
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Textarea } from "@/components/ui/textarea"
import { analyzeDuplicates, getDuplicateCandidates, type DuplicateGroup } from "@/features/commercial/duplicates"
import { useCommercialLeads } from "@/features/commercial/components/commercial-leads-provider"
import { useCommercialTeam } from "@/features/commercial/use-commercial-team"
import { useDoflowIdentity } from "@/features/identity/doflow-identity-provider"

const statuses = ["Da avviare", "Onboarding", "Attivo", "In attesa cliente", "Sospeso", "Completato"] as const
export function CustomerFormDialog({ open, onOpenChange }: { open: boolean; onOpenChange: (value: boolean) => void }) {
  const commercialTeam = useCommercialTeam()
  const identity = useDoflowIdentity()
  const store = useCommercialLeads(); const empty = { company: "", firstName: "", lastName: "", email: "", phone: "", vatNumber: "", taxCode: "", location: "", service: "", status: "Da avviare" as typeof statuses[number], assigneeId: identity.currentUserId, notes: "" }; const [form, setForm] = useState(empty); const [matches, setMatches] = useState<DuplicateGroup[]>([]); const [confirm, setConfirm] = useState(false)
  const set = (key: keyof typeof empty, value: string) => setForm((current) => ({ ...current, [key]: value }))
  const save = () => { const assigneeId = identity.hasCapability("canAssignLeads") ? form.assigneeId : identity.currentUserId; const owner = commercialTeam.find((item) => item.id === assigneeId)?.name ?? identity.currentUser.name; const id = store.createCustomer({ ...form, assigneeId, company: form.company.trim(), firstName: form.firstName.trim(), lastName: form.lastName.trim(), email: form.email.trim(), phone: form.phone.trim(), owner }); toast.success("Cliente creato"); setConfirm(false); setMatches([]); setForm({ ...empty, assigneeId: identity.currentUserId }); onOpenChange(false); return id }
  const submit = () => { if (!form.company.trim()) return; const preview = { id: "new-customer-preview", type: "client" as const, name: `${form.firstName} ${form.lastName}`.trim(), company: form.company, email: form.email, phone: form.phone, vatNumber: form.vatNumber, taxCode: form.taxCode }; const found = analyzeDuplicates([...getDuplicateCandidates(store.leads, store.customers), preview]).filter((group) => group.candidates.some((item) => item.id === preview.id)); if (found.length) { setMatches(found); return }; save() }
  const match = matches[0]?.candidates.find((item) => item.id !== "new-customer-preview")
  if (!identity.hasCapability("canEditCustomers")) return null
  const duplicateDialog = <AlertDialog open={matches.length > 0} onOpenChange={(value) => !value && setMatches([])}><AlertDialogContent className="w-[calc(100vw-2rem)] max-w-[560px] gap-5"><Button size="icon-sm" variant="ghost" className="absolute right-3 top-3" onClick={() => setMatches([])} aria-label="Chiudi"><X /></Button><AlertDialogHeader className="pr-9"><div className="mb-2 flex size-10 items-center justify-center rounded-lg bg-amber-500/15 text-amber-700 dark:text-amber-300"><AlertTriangle className="size-5" /></div><AlertDialogTitle>Possibile duplicato rilevato</AlertDialogTitle><AlertDialogDescription>Abbiamo trovato un record che potrebbe riferirsi alla stessa persona o azienda.</AlertDialogDescription></AlertDialogHeader>{match && <div className="rounded-lg border bg-muted/40 p-4"><div className="flex flex-wrap items-center gap-2"><p className="font-medium">{match.name || match.company}</p><span className="rounded-full bg-background px-2 py-0.5 text-xs">{match.type === "lead" ? "Lead" : match.type === "client" ? "Cliente" : "Contatto"}</span></div><p className="mt-1 text-sm text-muted-foreground">{match.company || "Azienda non disponibile"}</p><div className="mt-3 flex flex-wrap gap-1.5">{matches[0].matchingFields.map((field) => <span key={field} className="rounded-full bg-amber-500/15 px-2 py-1 text-xs font-medium text-amber-800 dark:text-amber-200">{field}</span>)}</div><p className="mt-3 text-sm text-muted-foreground">Controlla il record prima di crearne uno nuovo.</p></div>}<AlertDialogFooter className="block space-y-3"><div className="grid gap-2 sm:grid-cols-2">{match && <Button asChild className="w-full bg-violet-600 hover:bg-violet-700"><Link href={match.type === "lead" ? `/dashboard/commercial/leads/${match.id}` : `/dashboard/clienti/${match.customerId ?? match.id}`}>Apri record esistente</Link></Button>}<AlertDialogCancel className="m-0 w-full">Torna al modulo</AlertDialogCancel></div><div className="border-t pt-3"><p className="mb-2 text-sm text-muted-foreground">Sei sicuro che siano due record differenti?</p><Button variant="ghost" className="w-full justify-center text-amber-700 hover:bg-amber-500/10 hover:text-amber-800 dark:text-amber-300" onClick={() => { setMatches([]); setConfirm(true) }}>Crea comunque</Button></div></AlertDialogFooter></AlertDialogContent></AlertDialog>
  return <><Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[calc(100dvh-2rem)] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>Nuovo cliente</DialogTitle></DialogHeader><div className="grid gap-3 sm:grid-cols-2"><div className="sm:col-span-2"><Label>Nome o ragione sociale *</Label><Input value={form.company} onChange={(event) => set("company", event.target.value)} /></div><div><Label>Nome referente</Label><Input value={form.firstName} onChange={(event) => set("firstName", event.target.value)} /></div><div><Label>Cognome referente</Label><Input value={form.lastName} onChange={(event) => set("lastName", event.target.value)} /></div><div><Label>Email</Label><Input type="email" value={form.email} onChange={(event) => set("email", event.target.value)} /></div><div><Label>Telefono</Label><Input value={form.phone} onChange={(event) => set("phone", event.target.value)} /></div><div><Label>Partita IVA</Label><Input value={form.vatNumber} onChange={(event) => set("vatNumber", event.target.value)} /></div><div><Label>Codice fiscale</Label><Input value={form.taxCode} onChange={(event) => set("taxCode", event.target.value)} /></div><div className="sm:col-span-2"><Label>Indirizzo</Label><Input value={form.location} onChange={(event) => set("location", event.target.value)} /></div><div><Label>Servizio richiesto</Label><Input value={form.service} onChange={(event) => set("service", event.target.value)} /></div><div><Label>Stato</Label><Select value={form.status} onValueChange={(value) => set("status", value)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{statuses.map((item) => <SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent></Select></div><div><Label>Responsabile</Label><Select value={form.assigneeId} onValueChange={(value) => set("assigneeId", value)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{commercialTeam.map((item) => <SelectItem key={item.id} value={item.id}>{item.name}</SelectItem>)}</SelectContent></Select></div><div className="sm:col-span-2"><Label>Note</Label><Textarea value={form.notes} onChange={(event) => set("notes", event.target.value)} /></div></div><DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)}>Annulla</Button><Button disabled={!form.company.trim()} onClick={submit}>Crea cliente</Button></DialogFooter></DialogContent></Dialog>{duplicateDialog}<AlertDialog open={confirm} onOpenChange={setConfirm}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Creare comunque il cliente?</AlertDialogTitle><AlertDialogDescription>Verrà creato un solo cliente senza fondere dati.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Annulla</AlertDialogCancel><AlertDialogAction onClick={save}>Conferma creazione</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></>
}
