"use client"

import { useEffect, useMemo, useState } from "react"
import { useRouter } from "next/navigation"
import { Building2, CircleHelp, ClipboardCheck, FileSignature, FileText, FolderKanban, Megaphone, ReceiptText, Repeat2, ScanSearch, Search, ShoppingCart, UserRound, Waypoints } from "lucide-react"

import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Command, CommandDialog, CommandEmpty, CommandGroup, CommandInput, CommandItem, CommandList, CommandShortcut } from "@/components/ui/command"
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip"
import { useCommercialTeam } from "@/features/commercial/use-commercial-team"
import { formatOperationalValue, matchesOperationalSearch, normalizeOperationalSearch, operationalSearchTerms } from "@/features/commercial/commercial-formatters"
import { ProjectStatusBadge } from "@/features/commercial/components/project-status-badge"
import type { CommercialProject } from "@/features/commercial/components/commercial-leads-provider"
import { getProjectStatusVisual } from "@/features/commercial/commercial-production"
import { useAuthorizedCommercial } from "@/features/identity/use-authorized-commercial"
import { useFlowboards } from "@/features/flowboard/flowboard-provider"
import { useCompanyIntelligence } from "@/features/company-intelligence/company-intelligence-provider"
import { dashboardNavigationItems } from "@/components/app-sidebar"
import { useDoflowIdentity } from "@/features/identity/doflow-identity-provider"
import { useFlowExperience } from "@/features/flow/flow-experience-provider"
import { FlowEmptyState } from "@/features/flow/flow-empty-state"

type Result = { id: string; group: "Aiuto" | "Navigazione" | "Lead" | "Clienti" | "Progetti" | "Attività" | "Vendite" | "Ordini" | "Contratti" | "Rinnovi" | "Campagne" | "Preventivi" | "Fatture" | "Flowboard" | "Analisi azienda"; title: string; detail: string; status: string; projectStatus?: CommercialProject["status"]; due?: string; destination: string; icon: typeof Building2 }
const searchIn = (query: string, ...values: Array<string | undefined>) => normalizeOperationalSearch(values.filter(Boolean).join(" ")).includes(normalizeOperationalSearch(query))

export function GlobalSearch() {
  const commercialTeam = useCommercialTeam()
  const router = useRouter(); const identity = useDoflowIdentity(); const flow=useFlowExperience(); const { store, leads, customers, projects, activities } = useAuthorizedCommercial(); const flowboards = useFlowboards(); const intelligence = useCompanyIntelligence(); const [open, setOpen] = useState(false); const [query, setQuery] = useState("")
  useEffect(() => {
    const handleKeyDown = (event: KeyboardEvent) => {
      const modifier = event.ctrlKey || event.metaKey
      const key = event.key.toLowerCase()
      if (modifier && (key === "f" || key === "k")) {
        event.preventDefault()
        event.stopPropagation()
        setOpen(true)
      }
    }
    window.addEventListener("keydown", handleKeyDown, true)
    return () => window.removeEventListener("keydown", handleKeyDown, true)
  }, [])
  const results = useMemo<Result[]>(() => {
    if (!query.trim()) return []
    const helpDefinitions=[
      {id:"tour",title:"Avvia tutorial",detail:"Tour completo delle aree autorizzate",guide:""},
      {id:"dashboard",title:"Aiuto Dashboard",detail:"KPI, priorità e obiettivi",guide:"dashboard"},
      {id:"lead",title:"Come creo un lead?",detail:"Apri la guida Commerciale",guide:"commerciale"},
      {id:"convert",title:"Come converto un lead in cliente?",detail:"Segui Pipeline e scheda lead",guide:"pipeline"},
      {id:"activity",title:"Come creo un’attività?",detail:"Apri la guida Attività",guide:"attivita"},
      {id:"project",title:"Come apro un progetto?",detail:"Apri la guida Progetti",guide:"progetti"},
      {id:"team",title:"Come uso Team Space?",detail:"Messaggi e collaborazione",guide:"team-space"},
      {id:"call",title:"Come avvio una chiamata?",detail:"Chat, audio e video nello stesso canale",guide:"chat-call"},
    ]
    const allowedGuideIds=new Set(flow.availableGuides.map((item)=>item.id)); const helpResults=helpDefinitions.filter((item)=>!item.guide||allowedGuideIds.has(item.guide)).filter((item)=>searchIn(query,item.title,item.detail,"Flow aiuto tutorial")).map((item)=>({id:item.id,group:"Aiuto" as const,title:item.title,detail:item.detail,status:"Apri guida",destination:`flow:${item.guide}`,icon:CircleHelp}))
    const navigationResults = dashboardNavigationItems.flatMap((item) => {
      const children = item.items?.filter((child) => !child.capability || identity.hasCapability(child.capability)) ?? []
      const parentAllowed = !item.capability || identity.hasCapability(item.capability) || children.length > 0
      const entries = [...(parentAllowed ? [item] : []), ...children]
      return entries.filter((entry, index) => entries.findIndex((candidate) => candidate.title === entry.title && candidate.url === entry.url) === index).filter((entry) => searchIn(query, entry.title, item.title, entry.url.replaceAll("/", " "))).map((entry) => ({ id: entry.url, group: "Navigazione" as const, title: entry.title, detail: entry === item ? "Area del gestionale" : `In ${item.title}`, status: "Apri", destination: entry.url, icon: entry.icon ?? item.icon ?? Building2 }))
    })
    const leadResults = leads.filter((lead) => searchIn(query, lead.company, lead.firstName, lead.lastName, lead.email, lead.phone, lead.source, lead.service, ...(lead.services ?? []), ...operationalSearchTerms(lead.status))).map((lead) => ({ id: lead.id, group: "Lead" as const, title: lead.company, detail: `${lead.firstName} ${lead.lastName} · ${lead.email}`, status: formatOperationalValue(lead.status), destination: `/dashboard/commercial/leads/${lead.id}`, icon: UserRound }))
    const clientResults = customers.filter((client) => { const lead = leads.find((item) => item.id === client.sourceLeadId) ?? client.profile; return searchIn(query, lead.company, lead.firstName, lead.lastName, lead.email, lead.phone, lead.service, ...(lead.services ?? [])) }).map((client) => { const lead = leads.find((item) => item.id === client.sourceLeadId) ?? client.profile; return { id: client.id, group: "Clienti" as const, title: lead.company, detail: `Cliente · ${lead.firstName} ${lead.lastName}`, status: client.status, destination: `/dashboard/clienti/${client.id}`, icon: Building2 } })
    const projectResults = projects.filter((project) => { const client = customers.find((item) => item.id === project.clientId); const owner = commercialTeam.find((item) => item.id === project.ownerId)?.name; const visual = getProjectStatusVisual(project.status); return searchIn(query, project.name, client?.profile.company, project.service, owner, visual.label, ...operationalSearchTerms(project.priority)) }).map((project) => { const client = customers.find((item) => item.id === project.clientId); return { id: project.id, group: "Progetti" as const, title: project.name, detail: `Progetto · ${client?.profile.company ?? "Cliente"}`, status: getProjectStatusVisual(project.status).label, projectStatus: project.status, due: project.dueDate, destination: `/dashboard/progetti/${project.id}`, icon: FolderKanban } })
    const activityResults = activities.filter(({ activity, customer }) => { const project = projects.find((item) => item.id === activity.projectId); const owner = commercialTeam.find((item) => item.id === activity.assigneeId)?.name; return searchIn(query, activity.title, activity.description, customer.profile.company, project?.name, owner, ...operationalSearchTerms(activity.status), ...operationalSearchTerms(activity.priority), ...operationalSearchTerms(activity.type)) }).map(({ activity, customer }) => ({ id: activity.id, group: "Attività" as const, title: activity.title, detail: `Attività · ${customer.profile.company}`, status: formatOperationalValue(activity.status), due: activity.dueAt || activity.dueDate, destination: `/dashboard/attivita?activityId=${activity.id}`, icon: ClipboardCheck }))
    const saleResults = store.sales.filter((sale) => searchIn(query, sale.dealId, sale.origin, ...operationalSearchTerms(sale.status), store.services.find((service) => service.id === sale.serviceId)?.name, customers.find((customer) => customer.id === sale.customerId)?.profile.company, leads.find((lead) => lead.id === sale.leadId)?.company)).map((sale) => ({ id: sale.id, group: "Vendite" as const, title: customers.find((customer) => customer.id === sale.customerId)?.profile.company ?? leads.find((lead) => lead.id === sale.leadId)?.company ?? sale.dealId, detail: `Vendita · ${store.services.find((service) => service.id === sale.serviceId)?.name ?? "Servizio"}`, status: formatOperationalValue(sale.status), destination: "/dashboard/vendite", icon: ShoppingCart }))
    const orderResults = store.orders.filter((order) => searchIn(query, order.code, order.administrativeStatus, customers.find((customer) => customer.id === order.customerId)?.profile.company, ...order.items.map((item) => item.name))).map((order) => ({ id: order.id, group: "Ordini" as const, title: order.code, detail: `Ordine · ${customers.find((customer) => customer.id === order.customerId)?.profile.company ?? "Cliente autorizzato"}`, status: order.administrativeStatus, due: order.dueDate, destination: "/dashboard/ordini", icon: ReceiptText }))
    const contractResults = store.contracts.filter((contract) => searchIn(query, contract.code, contract.title, contract.signatoryName, customers.find((customer) => customer.id === contract.customerId)?.profile.company)).map((contract) => ({ id: contract.id, group: "Contratti" as const, title: contract.code, detail: `Contratto · ${customers.find((customer) => customer.id === contract.customerId)?.profile.company ?? "Cliente autorizzato"}`, status: contract.status, due: contract.signatureDueAt, destination: "/dashboard/contratti", icon: FileSignature }))
    const renewalResults = store.renewals.filter((renewal) => searchIn(query, renewal.planName, renewal.status, customers.find((customer) => customer.id === renewal.customerId)?.profile.company)).map((renewal) => ({ id: renewal.id, group: "Rinnovi" as const, title: renewal.planName, detail: `Rinnovo · ${customers.find((customer) => customer.id === renewal.customerId)?.profile.company ?? "Cliente autorizzato"}`, status: renewal.status, due: renewal.nextDueAt, destination: "/dashboard/rinnovi", icon: Repeat2 }))
    const campaignResults = store.campaigns.filter((campaign) => matchesOperationalSearch(query, campaign.name, campaign.account, campaign.channel, campaign.status)).map((campaign) => ({ id: campaign.id, group: "Campagne" as const, title: campaign.name, detail: `${formatOperationalValue(campaign.channel)} · ${campaign.account}`, status: formatOperationalValue(campaign.status), destination: "/dashboard/campagne", icon: Megaphone }))
    const quoteResults = store.quotes.filter((quote) => searchIn(query, quote.code, ...operationalSearchTerms(quote.status), quote.notes)).map((quote) => ({ id: quote.id, group: "Preventivi" as const, title: `${quote.code} · v${quote.version}`, detail: "Preventivo autorizzato", status: formatOperationalValue(quote.status), due: quote.validUntil, destination: "/dashboard/preventivi", icon: FileText }))
    const invoiceResults = store.invoices.filter((invoice) => searchIn(query, invoice.code, ...operationalSearchTerms(invoice.status), invoice.notes)).map((invoice) => ({ id: invoice.id, group: "Fatture" as const, title: invoice.code, detail: invoice.kind === "credit_note" ? "Nota di credito locale" : "Fattura locale", status: formatOperationalValue(invoice.status), due: invoice.dueAt, destination: "/dashboard/fatture", icon: ReceiptText }))
    const flowboardResults = flowboards.boards.filter((board) => !board.isTemplate && !board.archivedAt && searchIn(query, board.name, board.description, projects.find((project) => project.id === board.projectId)?.name)).map((board) => ({ id: board.id, group: "Flowboard" as const, title: board.name, detail: projects.find((project) => project.id === board.projectId)?.name ? `Flowboard · ${projects.find((project) => project.id === board.projectId)?.name}` : "Flowboard", status: board.status, destination: `/dashboard/flowboard/${board.id}`, icon: Waypoints }))
    const intelligenceResults = intelligence.reports.filter((report) => searchIn(query, report.companyName, report.domain, report.summary, ...report.findings.map((finding) => `${finding.label} ${finding.value}`))).map((report) => ({ id: report.id, group: "Analisi azienda" as const, title: report.companyName, detail: `Analisi · ${report.domain}`, status: report.status === "completed_without_ai" ? "Completata senza AI" : report.status, destination: `/dashboard/company-intelligence?report=${report.id}`, icon: ScanSearch }))
    return [...helpResults, ...navigationResults, ...leadResults, ...clientResults, ...projectResults, ...activityResults, ...saleResults, ...orderResults, ...contractResults, ...renewalResults, ...campaignResults, ...quoteResults, ...invoiceResults, ...flowboardResults, ...intelligenceResults]
  }, [activities, commercialTeam, customers, flow.availableGuides, flowboards.boards, identity, intelligence.reports, leads, projects, query, store.campaigns, store.contracts, store.invoices, store.orders, store.quotes, store.renewals, store.sales, store.services])
  const choose = (result: Result) => { setOpen(false); setQuery(""); if(result.destination.startsWith("flow:")){const guide=result.destination.slice(5);flow.startTour(guide||undefined);return}router.push(result.destination) }
  const groups = ["Aiuto", "Navigazione", "Lead", "Clienti", "Progetti", "Attività", "Vendite", "Ordini", "Contratti", "Rinnovi", "Campagne", "Preventivi", "Fatture", "Flowboard", "Analisi azienda"] as const
  return <><Tooltip><TooltipTrigger asChild><Button variant="outline" className="hidden h-9 w-[clamp(19rem,36vw,32.5rem)] justify-start gap-2 px-3 text-muted-foreground md:flex" onClick={() => setOpen(true)} aria-label="Apri ricerca globale"><Search className="size-4" /><span className="truncate">Cerca record, moduli e aiuto...</span><CommandShortcut className="ml-auto rounded border px-1.5 py-0.5 tracking-normal">Ctrl K</CommandShortcut></Button></TooltipTrigger><TooltipContent>Cerca nel gestionale</TooltipContent></Tooltip><Tooltip><TooltipTrigger asChild><Button variant="ghost" size="icon" className="md:hidden" onClick={() => setOpen(true)} aria-label="Apri ricerca globale"><Search /></Button></TooltipTrigger><TooltipContent>Ricerca globale</TooltipContent></Tooltip><CommandDialog open={open} onOpenChange={setOpen} title="Ricerca globale" description="Cerca record e comandi autorizzati nel gestionale" className="max-w-xl"><Command shouldFilter={false}><CommandInput value={query} onValueChange={setQuery} placeholder="Cerca record, moduli o una guida..." autoFocus /><CommandList>{!query.trim() ? <p className="px-3 py-8 text-center text-sm text-muted-foreground">Cerca un record oppure scrivi “aiuto”.</p> : results.length === 0 ? <CommandEmpty asChild><FlowEmptyState assetId="flow-empty-search" title="Nessun risultato" message="Controlla le parole cercate oppure prova un modulo o un comando di aiuto." /></CommandEmpty> : groups.map((group) => { const items = results.filter((result) => result.group === group).slice(0, 5); return items.length ? <CommandGroup key={group} heading={group}>{items.map((result) => { const Icon = result.icon; return <CommandItem key={`${result.group}-${result.id}`} value={`${result.group}-${result.id}`} onSelect={() => choose(result)}><Icon className="text-muted-foreground" /><div className="min-w-0 flex-1"><p className="truncate font-medium">{result.title}</p><p className="truncate text-xs text-muted-foreground">{result.detail}{result.due ? ` · ${result.due}` : ""}</p></div>{result.projectStatus ? <ProjectStatusBadge status={result.projectStatus} className="shrink-0 text-[10px]" /> : <Badge variant="secondary" className="shrink-0 text-[10px]">{result.status}</Badge>}</CommandItem> })}</CommandGroup> : null })}</CommandList></Command></CommandDialog></>
}
