"use client"

import { useEffect, useMemo, useState } from "react"
import { useRouter } from "next/navigation"
import { Building2, ClipboardCheck, FileSignature, FileText, FolderKanban, Megaphone, ReceiptText, Repeat2, Search, ShoppingCart, UserRound } from "lucide-react"

import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Command, CommandDialog, CommandEmpty, CommandGroup, CommandInput, CommandItem, CommandList, CommandShortcut } from "@/components/ui/command"
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip"
import { useCommercialTeam } from "@/features/commercial/use-commercial-team"
import { useAuthorizedCommercial } from "@/features/identity/use-authorized-commercial"

type Result = { id: string; group: "Lead" | "Clienti" | "Progetti" | "Attività" | "Vendite" | "Ordini" | "Contratti" | "Rinnovi" | "Campagne" | "Preventivi" | "Fatture"; title: string; detail: string; status: string; due?: string; destination: string; icon: typeof Building2 }
const normalize = (value: string) => value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLocaleLowerCase("it-IT")
const searchIn = (query: string, ...values: Array<string | undefined>) => normalize(values.filter(Boolean).join(" ")).includes(normalize(query))

export function GlobalSearch({ compact = false }: { compact?: boolean } = {}) {
  const router = useRouter(); const { store, leads, customers, projects, activities } = useAuthorizedCommercial(); const commercialTeam = useCommercialTeam(); const [open, setOpen] = useState(false); const [query, setQuery] = useState("")
  useEffect(() => {
    const handleKeyDown = (event: KeyboardEvent) => {
      const modifier = event.ctrlKey || event.metaKey
      const key = event.key.toLowerCase()
      if (modifier && (key === "f" || key === "k")) {
        event.preventDefault()
        event.stopPropagation()
        setOpen(true)
      }
    }
    window.addEventListener("keydown", handleKeyDown, true)
    return () => window.removeEventListener("keydown", handleKeyDown, true)
  }, [])
  const results = useMemo<Result[]>(() => {
    if (!query.trim()) return []
    const leadResults = leads.filter((lead) => searchIn(query, lead.company, lead.firstName, lead.lastName, lead.email, lead.phone, lead.source, lead.service, ...(lead.services ?? []))).map((lead) => ({ id: lead.id, group: "Lead" as const, title: lead.company, detail: `${lead.firstName} ${lead.lastName} · ${lead.email}`, status: lead.status, destination: `/dashboard/commercial/leads/${lead.id}`, icon: UserRound }))
    const clientResults = customers.filter((client) => { const lead = leads.find((item) => item.id === client.sourceLeadId) ?? client.profile; return searchIn(query, lead.company, lead.firstName, lead.lastName, lead.email, lead.phone, lead.service, ...(lead.services ?? [])) }).map((client) => { const lead = leads.find((item) => item.id === client.sourceLeadId) ?? client.profile; return { id: client.id, group: "Clienti" as const, title: lead.company, detail: `Cliente · ${lead.firstName} ${lead.lastName}`, status: client.status, destination: `/dashboard/clienti/${client.id}`, icon: Building2 } })
    const projectResults = projects.filter((project) => { const client = customers.find((item) => item.id === project.clientId); const owner = commercialTeam.find((item) => item.id === project.ownerId)?.name; return searchIn(query, project.name, client?.profile.company, project.service, owner) }).map((project) => { const client = customers.find((item) => item.id === project.clientId); return { id: project.id, group: "Progetti" as const, title: project.name, detail: `Progetto · ${client?.profile.company ?? "Cliente"}`, status: project.status, due: project.dueDate, destination: `/dashboard/progetti/${project.id}`, icon: FolderKanban } })
    const activityResults = activities.filter(({ activity, customer }) => { const project = projects.find((item) => item.id === activity.projectId); const owner = commercialTeam.find((item) => item.id === activity.assigneeId)?.name; return searchIn(query, activity.title, activity.description, customer.profile.company, project?.name, owner) }).map(({ activity, customer }) => ({ id: activity.id, group: "Attività" as const, title: activity.title, detail: `Attività · ${customer.profile.company}`, status: activity.status, due: activity.dueAt || activity.dueDate, destination: `/dashboard/attivita?activityId=${activity.id}`, icon: ClipboardCheck }))
    const saleResults = store.sales.filter((sale) => searchIn(query, sale.dealId, sale.origin, sale.status, store.services.find((service) => service.id === sale.serviceId)?.name, customers.find((customer) => customer.id === sale.customerId)?.profile.company, leads.find((lead) => lead.id === sale.leadId)?.company)).map((sale) => ({ id: sale.id, group: "Vendite" as const, title: customers.find((customer) => customer.id === sale.customerId)?.profile.company ?? leads.find((lead) => lead.id === sale.leadId)?.company ?? sale.dealId, detail: `Vendita · ${store.services.find((service) => service.id === sale.serviceId)?.name ?? "Servizio"}`, status: sale.status, destination: "/dashboard/vendite", icon: ShoppingCart }))
    const orderResults = store.orders.filter((order) => searchIn(query, order.code, order.administrativeStatus, customers.find((customer) => customer.id === order.customerId)?.profile.company, ...order.items.map((item) => item.name))).map((order) => ({ id: order.id, group: "Ordini" as const, title: order.code, detail: `Ordine · ${customers.find((customer) => customer.id === order.customerId)?.profile.company ?? "Cliente autorizzato"}`, status: order.administrativeStatus, due: order.dueDate, destination: "/dashboard/ordini", icon: ReceiptText }))
    const contractResults = store.contracts.filter((contract) => searchIn(query, contract.code, contract.title, contract.signatoryName, customers.find((customer) => customer.id === contract.customerId)?.profile.company)).map((contract) => ({ id: contract.id, group: "Contratti" as const, title: contract.code, detail: `Contratto · ${customers.find((customer) => customer.id === contract.customerId)?.profile.company ?? "Cliente autorizzato"}`, status: contract.status, due: contract.signatureDueAt, destination: "/dashboard/contratti", icon: FileSignature }))
    const renewalResults = store.renewals.filter((renewal) => searchIn(query, renewal.planName, renewal.status, customers.find((customer) => customer.id === renewal.customerId)?.profile.company)).map((renewal) => ({ id: renewal.id, group: "Rinnovi" as const, title: renewal.planName, detail: `Rinnovo · ${customers.find((customer) => customer.id === renewal.customerId)?.profile.company ?? "Cliente autorizzato"}`, status: renewal.status, due: renewal.nextDueAt, destination: "/dashboard/rinnovi", icon: Repeat2 }))
    const campaignResults = store.campaigns.filter((campaign) => searchIn(query, campaign.name, campaign.account, campaign.channel)).map((campaign) => ({ id: campaign.id, group: "Campagne" as const, title: campaign.name, detail: `${campaign.channel} · ${campaign.account}`, status: campaign.status, destination: "/dashboard/campagne", icon: Megaphone }))
    const quoteResults = store.quotes.filter((quote) => searchIn(query, quote.code, quote.status, quote.notes)).map((quote) => ({ id: quote.id, group: "Preventivi" as const, title: `${quote.code} · v${quote.version}`, detail: "Preventivo autorizzato", status: quote.status, due: quote.validUntil, destination: "/dashboard/preventivi", icon: FileText }))
    const invoiceResults = store.invoices.filter((invoice) => searchIn(query, invoice.code, invoice.status, invoice.notes)).map((invoice) => ({ id: invoice.id, group: "Fatture" as const, title: invoice.code, detail: invoice.kind === "credit_note" ? "Nota di credito locale" : "Fattura locale", status: invoice.status, due: invoice.dueAt, destination: "/dashboard/fatture", icon: ReceiptText }))
    return [...leadResults, ...clientResults, ...projectResults, ...activityResults, ...saleResults, ...orderResults, ...contractResults, ...renewalResults, ...campaignResults, ...quoteResults, ...invoiceResults]
  }, [activities, commercialTeam, customers, leads, projects, query, store.campaigns, store.contracts, store.invoices, store.orders, store.quotes, store.renewals, store.sales, store.services])
  const choose = (result: Result) => { setOpen(false); setQuery(""); router.push(result.destination) }
  const groups = ["Lead", "Clienti", "Progetti", "Attività", "Vendite", "Ordini", "Contratti", "Rinnovi", "Campagne", "Preventivi", "Fatture"] as const
  return <>{compact ? <Tooltip><TooltipTrigger asChild><Button variant="ghost" size="icon" onClick={() => setOpen(true)} aria-label="Apri ricerca globale"><Search /></Button></TooltipTrigger><TooltipContent>Ricerca globale</TooltipContent></Tooltip> : <Tooltip><TooltipTrigger asChild><Button variant="outline" className="h-9 w-full justify-start gap-2 bg-card/70 px-3 text-muted-foreground shadow-none backdrop-blur-sm" onClick={() => setOpen(true)} aria-label="Apri ricerca globale"><Search className="size-4" /><span className="truncate">Cerca record, moduli e aiuto...</span><CommandShortcut className="ml-auto rounded border px-1.5 py-0.5 tracking-normal">Ctrl K</CommandShortcut></Button></TooltipTrigger><TooltipContent>Cerca nel gestionale</TooltipContent></Tooltip>}<CommandDialog open={open} onOpenChange={setOpen} title="Ricerca globale" description="Cerca record autorizzati nel gestionale" className="max-w-xl"><Command shouldFilter={false}><CommandInput value={query} onValueChange={setQuery} placeholder="Cerca record, moduli e aiuto..." autoFocus /><CommandList>{!query.trim() ? <p className="px-3 py-8 text-center text-sm text-muted-foreground">Inizia a digitare per cercare nel gestionale.</p> : results.length === 0 ? <CommandEmpty>Nessun risultato trovato.</CommandEmpty> : groups.map((group) => { const items = results.filter((result) => result.group === group).slice(0, 5); return items.length ? <CommandGroup key={group} heading={group}>{items.map((result) => { const Icon = result.icon; return <CommandItem key={`${result.group}-${result.id}`} value={`${result.group}-${result.id}`} onSelect={() => choose(result)}><Icon className="text-muted-foreground" /><div className="min-w-0 flex-1"><p className="truncate font-medium">{result.title}</p><p className="truncate text-xs text-muted-foreground">{result.detail}{result.due ? ` · ${result.due}` : ""}</p></div><Badge variant="secondary" className="shrink-0 text-[10px]">{result.status}</Badge></CommandItem> })}</CommandGroup> : null })}</CommandList></Command></CommandDialog></>
}
