export enum BusinaroDepartment {
  ADMIN = 'ADMIN',
  TECH_OFFICE = 'TECH_OFFICE',
  WAREHOUSE = 'WAREHOUSE',
  MACHINE_TOOLS = 'MACHINE_TOOLS',
  ASSEMBLY = 'ASSEMBLY',
  PAINTING = 'PAINTING',
  PURCHASING = 'PURCHASING',
  PROD_DIRECTOR = 'PROD_DIRECTOR',
}

export enum ProductType {
  RAW_MATERIAL = 'RAW_MATERIAL',
  SEMI_FINISHED = 'SEMI_FINISHED',
  COMMERCIAL = 'COMMERCIAL',
  ASSEMBLY = 'ASSEMBLY',
  FINISHED_PRODUCT = 'FINISHED_PRODUCT',
  SERVICE_EXTERNAL = 'SERVICE_EXTERNAL',
}

export enum StockStatus {
  AVAILABLE = 'AVAILABLE',
  COMMITTED = 'COMMITTED',
  QC_PENDING = 'QC_PENDING',
  QUARANTINE = 'QUARANTINE',
  SCRAP = 'SCRAP',
}

export enum ConditionGrade {
  NEW = 'NEW',
  REFURBISHED = 'REFURBISHED',
  USED_AS_IS = 'USED_AS_IS',
  DAMAGED = 'DAMAGED',
}

export enum JobOrderType {
  PRODUCTION_NEW = 'PRODUCTION_NEW',
  SERVICE = 'SERVICE',
  INTERNAL = 'INTERNAL',
}
