import type { CommercialProject, CommercialProjectPhase, CustomerActivity } from "@/features/commercial/components/commercial-leads-provider"

export const productionProjectStatuses = ["not_started", "onboarding", "in_progress", "blocked", "qa_internal", "internal_review", "ready_client", "client_review", "changes_requested", "ready_publish", "published", "delivered", "support", "suspended", "cancelled"] as const
export type ProductionProjectStatus = (typeof productionProjectStatuses)[number]

export const productionProjectStatusLabels: Record<ProductionProjectStatus, string> = {
  not_started: "Da avviare", onboarding: "Onboarding", in_progress: "In lavorazione", blocked: "Bloccato", qa_internal: "QA interno", internal_review: "Revisione interna", ready_client: "Pronto per il cliente", client_review: "Revisione cliente", changes_requested: "Modifiche richieste", ready_publish: "Pronto alla pubblicazione", published: "Pubblicato", delivered: "Consegnato", support: "Assistenza", suspended: "Sospeso", cancelled: "Annullato",
}

export type ProjectTemplateDefinition = { name: string; phases: Array<{ name: string; estimatedMinutes: number; weight: number; role: "developer" | "project_manager"; visibility: "internal" | "client"; milestone?: boolean; checklist?: string[] }> }

const qa = ["Desktop verificato", "Tablet verificato", "Mobile verificato", "Form funzionanti", "Link controllati", "Nessun errore console", "SEO base", "Cookie/privacy", "Performance", "Immagini", "Testi", "Backup"]

export const projectTemplates: Record<string, ProjectTemplateDefinition> = {
  website: { name: "Sito vetrina", phases: ["Setup", "Raccolta materiali", "Struttura", "Homepage", "Pagine interne", "Responsive", "Form", "Integrazioni", "QA", "Revisione", "Pubblicazione", "Consegna"].map((name, index) => ({ name, estimatedMinutes: [90, 120, 180, 360, 480, 240, 120, 180, 240, 180, 120, 60][index], weight: [3, 5, 7, 14, 18, 10, 5, 7, 10, 8, 4, 2][index], role: name === "Raccolta materiali" || name === "Revisione" || name === "Consegna" ? "project_manager" : "developer", visibility: ["Raccolta materiali", "Revisione", "Pubblicazione", "Consegna"].includes(name) ? "client" : "internal", milestone: ["QA", "Pubblicazione", "Consegna"].includes(name), checklist: name === "QA" ? qa : undefined })) },
  landing: { name: "Landing page", phases: ["Brief", "Struttura", "Copy", "Design", "Sviluppo", "Responsive", "Form/Tracking", "QA", "Revisione", "Pubblicazione", "Consegna"].map((name, index) => ({ name, estimatedMinutes: [90, 120, 180, 240, 300, 120, 150, 180, 120, 60, 45][index], weight: [5, 7, 10, 14, 22, 9, 10, 11, 6, 4, 2][index], role: ["Brief", "Revisione", "Consegna"].includes(name) ? "project_manager" : "developer", visibility: ["Brief", "Revisione", "Pubblicazione", "Consegna"].includes(name) ? "client" : "internal", milestone: ["QA", "Pubblicazione", "Consegna"].includes(name), checklist: name === "QA" ? qa : undefined })) },
  ecommerce: { name: "E-commerce", phases: ["Setup", "Catalogo", "Pagamenti", "Spedizioni", "Pagine", "Checkout", "Email", "Responsive", "Test ordine", "QA", "Revisione", "Pubblicazione", "Consegna"].map((name, index) => ({ name, estimatedMinutes: [120, 600, 240, 180, 480, 360, 180, 300, 240, 300, 240, 120, 60][index], weight: [3, 17, 7, 5, 14, 11, 5, 9, 7, 9, 7, 4, 2][index], role: ["Revisione", "Consegna"].includes(name) ? "project_manager" : "developer", visibility: ["Catalogo", "Revisione", "Pubblicazione", "Consegna"].includes(name) ? "client" : "internal", milestone: ["Test ordine", "QA", "Pubblicazione", "Consegna"].includes(name), checklist: name === "QA" ? qa : undefined })) },
  software: genericTemplate("Software"), saas: genericTemplate("Gestionale SaaS"), marketing: genericTemplate("Marketing"), maintenance: genericTemplate("Assistenza"), other: genericTemplate("Altro"),
}

function genericTemplate(name: string): ProjectTemplateDefinition { return { name, phases: ["Analisi", "Pianificazione", "Produzione", "QA", "Revisione", "Consegna"].map((phase, index) => ({ name: phase, estimatedMinutes: [180, 120, 600, 240, 180, 60][index], weight: [12, 8, 45, 18, 12, 5][index], role: ["Analisi", "Pianificazione", "Revisione", "Consegna"].includes(phase) ? "project_manager" : "developer", visibility: ["Analisi", "Revisione", "Consegna"].includes(phase) ? "client" : "internal", milestone: ["QA", "Consegna"].includes(phase), checklist: phase === "QA" ? qa : undefined })) } }

export function activityWeight(activity: CustomerActivity) { return activity.weight ?? Math.max(1, activity.estimatedMinutes ?? 30) }
export function weightedProgress(activities: CustomerActivity[], visibility?: "internal" | "client") { const eligible = activities.filter((activity) => !activity.archivedAt && activity.status !== "Annullata" && (!visibility || activity.visibility === visibility)); const total = eligible.reduce((sum, activity) => sum + activityWeight(activity), 0); const complete = eligible.filter((activity) => activity.status === "Completata").reduce((sum, activity) => sum + activityWeight(activity), 0); return total ? Math.round(complete / total * 100) : 0 }
export function projectProgress(project: CommercialProject, activities: CustomerActivity[]) { const linked = activities.filter((activity) => activity.projectId === project.id); return { internal: weightedProgress(linked), client: weightedProgress(linked.filter((activity) => activity.clientVisibleAt), "client"), estimatedMinutes: linked.filter((activity) => activity.status !== "Annullata" && !activity.archivedAt).reduce((sum, activity) => sum + (activity.estimatedMinutes ?? 0), 0) } }
export function phaseProgressWeighted(phase: CommercialProjectPhase, activities: CustomerActivity[]) { return weightedProgress(activities.filter((activity) => activity.phaseId === phase.id)) }
