"use client"

import { useMemo, useState } from "react"
import { CheckCircle2, Coins, HandCoins, History, LoaderCircle, ShieldCheck, WalletCards } from "lucide-react"
import { toast } from "sonner"

import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Textarea } from "@/components/ui/textarea"
import { useBonus, type BonusPolicyDto } from "@/features/bonus/bonus-provider"
import { useDoflowIdentity } from "@/features/identity/doflow-identity-provider"

const euro = new Intl.NumberFormat("it-IT", { style: "currency", currency: "EUR" })
const dateTime = new Intl.DateTimeFormat("it-IT", { dateStyle: "medium", timeStyle: "short" })
const requestLabels: Record<string, string> = { submitted: "In attesa di approvazione", approved: "Approvato", rejected: "Rifiutato", processing: "In liquidazione", paid: "Liquidato", reversed: "Stornato", cancelled: "Annullato" }

export function BonusPage() {
  const bonus = useBonus(); const identity = useDoflowIdentity(); const snapshot = bonus.snapshot
  const [points, setPoints] = useState(""); const [reason, setReason] = useState(""); const [busy, setBusy] = useState(false)
  const [decisionReasons, setDecisionReasons] = useState<Record<string, string>>({}); const [references, setReferences] = useState<Record<string, string>>({})
  const run = async (task: () => Promise<{ ok: boolean; message?: string }>, success: string) => { setBusy(true); try { const result = await task(); if (result.ok) toast.success(success); else toast.error(result.message || "Operazione non riuscita") } finally { setBusy(false) } }
  const wallet = snapshot?.wallet
  const indicative = (wallet?.consolidatedPoints ?? 0) * (snapshot?.policy.pointEuroCents ?? 50) / 100
  const approvedEuro = snapshot?.requests.filter((item) => ["approved", "processing"].includes(item.status)).reduce((sum, item) => sum + item.euroCents, 0) ?? 0
  const paidEuro = snapshot?.requests.filter((item) => item.status === "paid").reduce((sum, item) => sum + item.euroCents, 0) ?? 0
  const capProgress = Math.min(100, ((wallet?.consolidatedPoints ?? 0) / (snapshot?.policy.monthlyCapPoints || 600)) * 100)
  const sortedLedger = useMemo(() => [...(snapshot?.ledger ?? [])].sort((a, b) => b.occurredAt.localeCompare(a.occurredAt)), [snapshot?.ledger])

  if (bonus.loading && !snapshot) return <main className="grid min-h-64 place-items-center" aria-busy="true"><LoaderCircle className="size-6 animate-spin text-primary"/></main>
  if (!snapshot || !wallet) return <main className="p-4 md:p-6"><Card className="border-destructive/40"><CardHeader><CardTitle>Portafoglio non disponibile</CardTitle><CardDescription>{bonus.error ?? "Riprova tra poco."}</CardDescription></CardHeader><CardContent><Button onClick={() => void bonus.refresh()}>Riprova</Button></CardContent></Card></main>

  return <main className="w-full space-y-5 p-4 md:p-6">
    <header className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-primary">Personale</p><h1 className="flex items-center gap-2 text-2xl font-semibold"><WalletCards className="size-6"/>Portafoglio punti</h1><p className="text-sm text-muted-foreground">Punti consolidati, valore indicativo e richieste volontarie. Il valore diventa liquidabile soltanto dopo approvazione.</p></div><Badge variant="outline">Persistenza server · policy v{snapshot.policy.version}</Badge></header>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Kpi label="Punti maturati" value={`${wallet.consolidatedPoints} pt`} detail={`${wallet.provisionalPoints} pt provvisori`}/><Kpi label="Valore indicativo" value={euro.format(indicative)} detail="Non ancora liquidabile"/><Kpi label="Bonus approvato" value={euro.format(approvedEuro / 100)} detail={`${wallet.lockedPoints} pt bloccati`}/><Kpi label="Bonus liquidato" value={euro.format(paidEuro / 100)} detail={`${wallet.redeemedPoints} pt utilizzati`}/></section>
    <Card><CardContent className="space-y-2 p-4"><div className="flex items-center justify-between gap-3 text-sm"><span>Progresso verso il tetto mensile</span><strong>{wallet.consolidatedPoints} / {snapshot.policy.monthlyCapPoints} pt</strong></div><div className="h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-violet-500" style={{ width: `${capProgress}%` }}/></div><p className="text-xs text-muted-foreground">100 punti approvati corrispondono a {euro.format(100 * snapshot.policy.pointEuroCents / 100)} indicativi. Il valore diventa liquidabile soltanto dopo approvazione e consolidamento mensile. Riserva minima: {snapshot.policy.reservePoints} pt.</p></CardContent></Card>
    <Tabs defaultValue="movements"><TabsList className="h-auto w-full justify-start overflow-x-auto"><TabsTrigger value="movements">Movimenti</TabsTrigger><TabsTrigger value="requests">Richieste</TabsTrigger>{snapshot.canManage&&<TabsTrigger value="approvals">Approvazioni</TabsTrigger>}</TabsList>
      <TabsContent value="movements" className="space-y-2">{sortedLedger.map((entry)=><Card key={entry.id}><CardContent className="flex items-start gap-3 p-4"><span className={`grid size-9 shrink-0 place-items-center rounded-full ${entry.points >= 0 ? "bg-emerald-500/10 text-emerald-600" : "bg-rose-500/10 text-rose-600"}`}><Coins className="size-4"/></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><strong>{entry.points > 0 ? "+" : ""}{entry.points} pt · {entry.points > 0 ? "+" : ""}{euro.format(entry.points * snapshot.policy.pointEuroCents / 100)}</strong><Badge variant="outline">{entry.bucket === "provisional" ? "Provvisorio" : entry.status === "reversed" ? "Stornato" : "Consolidato"}</Badge></div><p className="text-sm">{entry.reason}</p><p className="text-xs text-muted-foreground">{dateTime.format(new Date(entry.occurredAt))} · {entry.rule}</p></div></CardContent></Card>)}{!sortedLedger.length&&<Empty text="Nessun movimento nel portafoglio."/>}</TabsContent>
      <TabsContent value="requests" className="space-y-4"><Card><CardHeader><CardTitle className="text-base">Richiedi un bonus</CardTitle><CardDescription>Disponibili {wallet.availablePoints} pt; devono restare almeno {snapshot.policy.reservePoints} pt. Minimo {snapshot.policy.minimumRequestPoints} pt, tetto mensile {snapshot.policy.monthlyCapPoints} pt.</CardDescription></CardHeader><CardContent className="grid gap-3 md:grid-cols-[180px_1fr_auto]"><div><Label htmlFor="bonus-points">Punti</Label><Input id="bonus-points" type="number" min={snapshot.policy.minimumRequestPoints} value={points} onChange={(event)=>setPoints(event.target.value)}/></div><div><Label htmlFor="bonus-reason">Motivazione</Label><Input id="bonus-reason" value={reason} onChange={(event)=>setReason(event.target.value)} placeholder="Come desideri utilizzare il bonus"/></div><Button className="self-end" disabled={busy || !points || !reason.trim()} onClick={()=>void run(async()=>{const result=await bonus.action({action:"request",points:Number(points),reason,idempotencyKey:crypto.randomUUID()}); if(result.ok){setPoints("");setReason("")} return result},"Richiesta inviata")}>Invia richiesta</Button></CardContent></Card>{snapshot.requests.map((item)=><RequestCard key={item.id} request={item}/>)}{!snapshot.requests.length&&<Empty text="Nessuna richiesta inviata."/>}</TabsContent>
      {snapshot.canManage&&<TabsContent value="approvals" className="space-y-3">{snapshot.pendingRequests.map((item)=><Card key={item.id}><CardContent className="space-y-3 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><strong>{item.code} · {identity.users.find((user)=>user.id===item.userId)?.name ?? item.userId}</strong><p className="text-sm text-muted-foreground">{item.points} pt · {euro.format(item.euroCents/100)}</p></div><Badge variant="outline">{requestLabels[item.status]??item.status}</Badge></div>{item.status==="submitted"&&<><Label htmlFor={`decision-${item.id}`}>Motivazione decisione</Label><Textarea id={`decision-${item.id}`} value={decisionReasons[item.id]??""} onChange={(event)=>setDecisionReasons((current)=>({...current,[item.id]:event.target.value}))}/><div className="flex gap-2"><Button variant="outline" disabled={busy||!(decisionReasons[item.id]??"").trim()||item.userId===identity.currentUserId} onClick={()=>void run(()=>bonus.action({action:"decide",requestId:item.id,approve:false,reason:decisionReasons[item.id],idempotencyKey:`decision:${item.id}:reject`}),"Richiesta rifiutata")}>Rifiuta</Button><Button disabled={busy||!(decisionReasons[item.id]??"").trim()||item.userId===identity.currentUserId} onClick={()=>void run(()=>bonus.action({action:"decide",requestId:item.id,approve:true,reason:decisionReasons[item.id],idempotencyKey:`decision:${item.id}:approve`}),"Richiesta approvata")}><CheckCircle2/>Approva</Button></div></>}{item.status==="approved"&&<div className="grid gap-2 sm:grid-cols-[1fr_auto]"><Input aria-label={`Riferimento liquidazione ${item.code}`} value={references[item.id]??""} onChange={(event)=>setReferences((current)=>({...current,[item.id]:event.target.value}))} placeholder="Riferimento pagamento interno"/><Button disabled={busy||!(references[item.id]??"").trim()} onClick={()=>void run(()=>bonus.action({action:"payout",requestId:item.id,reference:references[item.id],idempotencyKey:`payout:${item.id}`}),"Bonus liquidato")}><HandCoins/>Segna liquidato</Button></div>}</CardContent></Card>)}{!snapshot.pendingRequests.length&&<Empty text="Nessuna richiesta da elaborare."/>}</TabsContent>}
    </Tabs>
    <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><ShieldCheck className="size-4"/>Regolamento applicato</CardTitle></CardHeader><CardContent className="grid gap-2 text-sm md:grid-cols-2"><p>1 punto approvato = <strong>{euro.format(snapshot.policy.pointEuroCents/100)}</strong> indicativi.</p><p>Incassi commerciali: 1 punto ogni <strong>{euro.format(snapshot.policy.collectedEuroPerPoint)}</strong> netti.</p><p>Soglia richiesta: <strong>{snapshot.policy.minimumRequestPoints} pt</strong>.</p><p>Tetto mensile: <strong>{snapshot.policy.monthlyCapPoints} pt · {euro.format(snapshot.policy.monthlyCapPoints*snapshot.policy.pointEuroCents/100)}</strong>.</p></CardContent></Card>
  </main>
}

export function BonusAdministrationSettings() {
  const bonus = useBonus(); const identity = useDoflowIdentity(); const policy = bonus.snapshot?.policy
  const [draft, setDraft] = useState<Record<string, string>>({}); const [userId, setUserId] = useState("team-marta"); const [adjustment, setAdjustment] = useState(""); const [reason, setReason] = useState("")
  if (!bonus.snapshot?.canManage || !policy) return null
  const field = (key: keyof BonusPolicyDto, fallback: number) => Number(draft[key] ?? fallback)
  return <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><ShieldCheck className="size-4"/>Portafoglio punti e bonus</CardTitle><CardDescription>Ogni modifica crea una nuova versione: i periodi consolidati mantengono la conversione originale.</CardDescription></CardHeader><CardContent className="space-y-5"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{([
    ["pointEuroCents","Cent per punto",policy.pointEuroCents],
    ["minimumRequestPoints","Soglia richiesta",policy.minimumRequestPoints],
    ["reservePoints","Riserva minima",policy.reservePoints],
    ["monthlyCapPoints","Tetto mensile",policy.monthlyCapPoints],
    ["collectedEuroPerPoint","Euro incassati per punto",policy.collectedEuroPerPoint],
  ] as const).map(([key,label,value])=><div key={key}><Label htmlFor={`bonus-policy-${key}`}>{label}</Label><Input id={`bonus-policy-${key}`} type="number" min="1" value={draft[key]??String(value)} onChange={(event)=>setDraft((current)=>({...current,[key]:event.target.value}))}/></div>)}</div><Button onClick={()=>void (async()=>{const result=await bonus.action({action:"policy",pointEuroCents:field("pointEuroCents",policy.pointEuroCents),minimumRequestPoints:field("minimumRequestPoints",policy.minimumRequestPoints),reservePoints:field("reservePoints",policy.reservePoints),monthlyCapPoints:field("monthlyCapPoints",policy.monthlyCapPoints),collectedEuroPerPoint:field("collectedEuroPerPoint",policy.collectedEuroPerPoint),idempotencyKey:crypto.randomUUID()}); if(result.ok){setDraft({});toast.success("Nuova versione del regolamento salvata")}else toast.error(result.message)})()}>Salva nuova versione</Button>
    <div className="rounded-xl border p-4"><h3 className="font-medium">Rettifica append-only</h3><p className="mb-3 text-xs text-muted-foreground">Bonus e penalità richiedono una motivazione; il movimento originale non viene riscritto.</p><div className="grid gap-3 sm:grid-cols-3"><select aria-label="Collaboratore rettifica" className="h-9 rounded-md border bg-transparent px-3 text-sm" value={userId} onChange={(event)=>setUserId(event.target.value)}>{identity.users.map((user)=><option key={user.id} value={user.id}>{user.name}</option>)}</select><Input aria-label="Punti rettifica" type="number" value={adjustment} onChange={(event)=>setAdjustment(event.target.value)} placeholder="+10 oppure -5"/><Input aria-label="Motivazione rettifica" value={reason} onChange={(event)=>setReason(event.target.value)} placeholder="Motivazione obbligatoria"/></div><Button className="mt-3" disabled={!adjustment||!reason.trim()} onClick={()=>void (async()=>{const result=await bonus.action({action:"adjustment",userId,points:Number(adjustment),reason,idempotencyKey:crypto.randomUUID()}); if(result.ok){setAdjustment("");setReason("");toast.success("Rettifica registrata")}else toast.error(result.message)})()}>Registra movimento</Button></div>
    <Button variant="outline" asChild><a href="/dashboard/bonus">Apri richieste e approvazioni</a></Button>
  </CardContent></Card>
}

function Kpi({label,value,detail}:{label:string;value:string;detail:string}){return <Card><CardContent className="p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-semibold tabular-nums">{value}</p><p className="mt-1 text-xs text-muted-foreground">{detail}</p></CardContent></Card>}
function Empty({text}:{text:string}){return <div className="rounded-xl border border-dashed p-8 text-center text-sm text-muted-foreground">{text}</div>}
function RequestCard({request}:{request: import("@/features/bonus/bonus-provider").BonusRequestDto}){return <Card><CardContent className="flex flex-wrap items-center gap-3 p-4"><History className="size-4"/><div className="min-w-0 flex-1"><p className="font-medium">{request.code} · {request.points} pt</p><p className="text-xs text-muted-foreground">{request.submittedAt?dateTime.format(new Date(request.submittedAt)):"Bozza"}</p></div><Badge variant="outline">{requestLabels[request.status]??request.status}</Badge></CardContent></Card>}
