"use client"
/* eslint-disable @typescript-eslint/no-unused-vars */
import { useState } from "react"
import Link from "next/link"
import { Area, AreaChart, CartesianGrid, XAxis, YAxis } from "recharts"
import { BadgeEuro, CalendarDays, ChartNoAxesCombined, CheckCircle2, ChevronDown, ChevronRight, CircleDollarSign, ContactRound, ListTodo, ReceiptText, Sparkles, Target, TrendingUp, Trophy, UsersRound } from "lucide-react"
import { Avatar, AvatarFallback } from "@/components/ui/avatar"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card"
import { ChartContainer, ChartLegend, ChartLegendContent, ChartTooltip, ChartTooltipContent, type ChartConfig } from "@/components/ui/chart"
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu"
import { Progress } from "@/components/ui/progress"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { ScrollArea, ScrollBar } from "@/components/ui/scroll-area"
import { Separator } from "@/components/ui/separator"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Calendar } from "@/components/ui/calendar"
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover"
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip"
import { MetricAreaChart } from "@/features/dashboard/components/metric-area-chart"
import { FinancialSummaryChart } from "@/features/dashboard/components/financial-summary-chart"
import { activeClientsFixtures, dashboardActivities, dashboardDeadlines, dashboardProjects, missionObjectives, monthlyMission, overviewRangeFixtures } from "@/features/dashboard/data/dashboard-fixtures"
import { getMetricTrend } from "@/features/dashboard/trend"
import type { DashboardRange, StatusTone } from "@/features/dashboard/types"
import { useDoflowIdentity } from "@/features/identity/doflow-identity-provider"
import { useAuthorizedCommercial } from "@/features/identity/use-authorized-commercial"
import { roleLabels } from "@/features/identity/permissions"
import { RankingWinnerBadges } from "@/features/commercial/components/ranking-winner-badges"
import { SynchronizedDashboardOverview } from "@/features/dashboard/synchronized-dashboard-overview"

const config = { roas: { label: "ROAS", color: "var(--chart-1)" }, ctr: { label: "CTR", color: "var(--chart-2)" } } satisfies ChartConfig
const tone: Record<StatusTone, string> = { neutral: "border-border bg-muted text-muted-foreground", warning: "border-amber-500/30 bg-amber-500/10 text-amber-700 dark:text-amber-300", destructive: "border-destructive/30 bg-destructive/10 text-destructive", success: "border-emerald-500/30 bg-emerald-500/10 text-emerald-700 dark:text-emerald-300" }
const projects = dashboardProjects
const priorities: Array<{id:string;title:string;detail:string;time:string;initials:string;tone:StatusTone}> = dashboardActivities.map((activity) => ({ id: activity.id, title: activity.title, detail: activity.client, time: activity.time, initials: activity.assignee, tone: activity.priority === "Urgente" ? "destructive" : activity.priority === "Alta" ? "warning" : activity.priority === "Completata" ? "success" : "neutral" }))
const deadlines = dashboardDeadlines
const euro = new Intl.NumberFormat("it-IT", { style: "currency", currency: "EUR", useGrouping: "always", maximumFractionDigits: 0 })
const objectiveProgress = (current: number, target: number) => Math.round(current / target * 100)
const objectiveValue = (objective: typeof monthlyMission.objectives[number]) => objective.format === "currency" ? `${euro.format(objective.current)} / ${euro.format(objective.target)}` : `${objective.current} / ${objective.target} ${objective.suffix}`
function BadgeTone({ tone: kind, children }: { tone: StatusTone; children: React.ReactNode }) { return <Badge variant="outline" className={tone[kind]}>{children}</Badge> }
function Menu({ label }: { label: string }) { return <DropdownMenu><DropdownMenuTrigger asChild><Button variant="outline" size="sm">{label}<ChevronDown /></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem>7 giorni</DropdownMenuItem><DropdownMenuItem>30 giorni</DropdownMenuItem><DropdownMenuItem>90 giorni</DropdownMenuItem></DropdownMenuContent></DropdownMenu> }
function Status({ value }: { value: string }) { return <BadgeTone tone={value === "Completato" ? "success" : value === "A rischio" ? "warning" : value === "In ritardo" ? "destructive" : "neutral"}>{value}</BadgeTone> }
function getGoalProgressStatus(percentage:number) { const status = percentage >= 100 ? { label: "Completato", tone: "success" as StatusTone } : percentage >= 75 ? { label: "In linea", tone: "success" as StatusTone } : percentage >= 50 ? { label: "A rischio", tone: "warning" as StatusTone } : percentage >= 25 ? { label: "In ritardo", tone: "destructive" as StatusTone } : { label: "Critico", tone: "destructive" as StatusTone }; return { ...status, generalClass: percentage >= 100 ? "[&_[data-slot=progress-indicator]]:bg-emerald-600" : percentage >= 75 ? "[&_[data-slot=progress-indicator]]:bg-emerald-500" : percentage >= 50 ? "[&_[data-slot=progress-indicator]]:bg-amber-500" : "[&_[data-slot=progress-indicator]]:bg-red-500", objectiveClass: percentage >= 100 ? "[&_[data-slot=progress-indicator]]:bg-emerald-600 text-emerald-700 dark:text-emerald-300" : "[&_[data-slot=progress-indicator]]:bg-foreground text-foreground" } }
function getProjectDeadline(deadlineDate:string) { const today = new Date("2026-08-18T00:00:00"); const deadline = new Date(`${deadlineDate}T00:00:00`); const days = Math.round((deadline.getTime() - today.getTime()) / 86_400_000); if (days < 0) return { order: 0, tone: "destructive" as StatusTone, label: "Scaduto" }; if (days === 0) return { order: 1, tone: "destructive" as StatusTone, label: "Oggi" }; if (days <= 7) return { order: 2, tone: "warning" as StatusTone, label: "Vicino" }; return { order: 3, tone: "neutral" as StatusTone, label: "Regolare" } }

export function DashboardOverview() {
 return <SynchronizedDashboardOverview />
}
export function Mission(){const icons=[CircleDollarSign,Trophy,Target,CheckCircle2,CalendarDays]; return <Card className="@xl/main:col-span-4"><CardHeader><div className="flex items-start justify-between gap-2"><div><div className="flex items-center gap-2"><Sparkles className="size-4 text-muted-foreground"/><CardTitle>Missione del mese</CardTitle></div><CardDescription>Completa gli obiettivi operativi di agosto</CardDescription></div><Menu label="Questo mese"/></div></CardHeader><CardContent className="space-y-3"><div className="flex items-end gap-2"><span className="text-3xl font-semibold">72%</span><Badge variant="secondary">3 di 5</Badge></div><Progress value={72}/><div className="grid grid-cols-2 gap-2 text-xs"><span className="text-muted-foreground">13 giorni rimanenti</span><span className="text-right text-muted-foreground">Prossimo: € 35.000</span></div><p className="text-sm text-muted-foreground">Sei al 72%. Completa altri 2 obiettivi per raggiungere il prossimo traguardo.</p><Separator/>{missionObjectives.slice(0,5).map((o,i)=>{const Icon=icons[i];return <div key={o.label} className="space-y-1.5"><div className="flex items-center gap-2 text-sm"><Icon className="size-3.5 text-muted-foreground"/><span className="min-w-0 flex-1 truncate">{o.label}</span><Tooltip><TooltipTrigger asChild><span><Status value={o.status}/></span></TooltipTrigger><TooltipContent>{o.current} su {o.target}</TooltipContent></Tooltip></div><div className="flex items-center gap-2"><Progress value={o.progress}/><span className="text-xs tabular-nums">{o.progress}%</span></div></div>})}</CardContent><CardFooter><Button variant="link" size="sm" className="px-0">Vedi tutti gli obiettivi <ChevronRight/></Button></CardFooter></Card>}
export function Operations(){return <Card className="@xl/main:col-span-4"><CardHeader><CardTitle>Operatività</CardTitle></CardHeader></Card>}
export function Projects(){return <Card className="@xl/main:col-span-4"><CardHeader><CardTitle>Progetti in corso</CardTitle></CardHeader></Card>}
function Campaigns({data}:{data:typeof overviewRangeFixtures["30d"]}){return <section className="grid gap-4 @xl/main:col-span-8 @lg/main:grid-cols-12"><Card className="@lg/main:col-span-5"><CardHeader><CardTitle>Performance campagne</CardTitle><div className="grid grid-cols-2 gap-2 text-sm"><Stat n="ROAS" v={data.campaignPerformance.roas}/><Stat n="CTR" v={data.campaignPerformance.ctr}/><Stat n="Conversioni" v={data.campaignPerformance.conversions}/><Stat n="Budget" v={data.campaignPerformance.budget}/></div></CardHeader><CardContent><ChartContainer config={config} className="h-64 w-full"><AreaChart data={data.campaignPerformance.series} margin={{left:-18}}><CartesianGrid vertical={false}/><XAxis dataKey="month" tickLine={false} axisLine={false}/><YAxis yAxisId="r" tickLine={false} axisLine={false}/><YAxis yAxisId="c" orientation="right" tickLine={false} axisLine={false}/><ChartTooltip content={<ChartTooltipContent indicator="dot"/>}/><ChartLegend content={<ChartLegendContent/>}/><Area yAxisId="r" dataKey="roas" type="natural" stroke="var(--color-roas)" fill="var(--color-roas)" fillOpacity={.12}/><Area yAxisId="c" dataKey="ctr" type="natural" stroke="var(--color-ctr)" fill="var(--color-ctr)" fillOpacity={.1}/></AreaChart></ChartContainer></CardContent></Card><Card className="@lg/main:col-span-7"><CardHeader><div className="flex justify-between gap-2"><CardTitle>Top campagne</CardTitle><Menu label="Questo mese"/></div></CardHeader><CardContent className="px-0"><ScrollArea><div className="min-w-180 px-4"><Table><TableHeader><TableRow><TableHead>Campagna</TableHead><TableHead>ROAS</TableHead><TableHead>CTR</TableHead><TableHead>Conversioni</TableHead><TableHead>Budget</TableHead></TableRow></TableHeader><TableBody>{data.topCampaigns.map(x=><TableRow key={x.campaign}><TableCell className="font-medium">{x.campaign}</TableCell><TableCell><Badge variant="secondary">{x.roas}</Badge></TableCell><TableCell>{x.ctr}</TableCell><TableCell>{x.conversions}</TableCell><TableCell>{x.budget}</TableCell></TableRow>)}</TableBody></Table></div><ScrollBar orientation="horizontal"/></ScrollArea></CardContent><CardFooter><Button variant="link" size="sm" className="px-0">Vedi tutte le campagne <ChevronRight/></Button></CardFooter></Card></section>}
function Stat({n,v}:{n:string;v:string}){return <div><p className="text-xs text-muted-foreground">{n}</p><p className="font-medium">{v}</p></div>}
function OperationalRow({range}:{range:DashboardRange}) { return <section className="grid items-stretch gap-4 @xl/main:grid-cols-12"><PrioritiesStandalone/><ProjectsStandalone/><ActiveClientsCard metric={activeClientsFixtures[range]}/></section> }
function PrioritiesStandalone() { return <Card className="flex h-full flex-col @xl/main:col-span-4"><CardHeader><CardTitle>Priorità di oggi</CardTitle><CardDescription>Le attività da non perdere</CardDescription></CardHeader><CardContent className="flex-1 space-y-3">{priorities.map((item,index) => <div key={item.id}><Link href={`/activities/${item.id}`} aria-label={`Apri attività ${item.title} per ${item.detail}`} className="block cursor-pointer rounded-md outline-none transition-colors hover:bg-muted/50 focus-visible:ring-2 focus-visible:ring-ring"><div className="flex items-center gap-3 p-1.5"><ListTodo className="size-4 shrink-0 text-muted-foreground"/><div className="min-w-0 flex-1"><p className="text-sm font-medium">{item.title}</p><p className="text-xs text-muted-foreground">{item.detail}</p></div><BadgeTone tone={item.tone}>{item.tone === "destructive" ? "Urgente" : item.tone === "warning" ? "Alta" : item.tone === "success" ? "Completata" : "Normale"}</BadgeTone><span className="text-xs tabular-nums">{item.time}</span><Avatar size="sm"><AvatarFallback>{item.initials}</AvatarFallback></Avatar></div></Link>{index < priorities.length - 1 && <Separator className="mt-3"/>}</div>)} </CardContent><CardFooter className="mt-auto"><Button asChild variant="link" size="sm" className="px-0"><Link href="/activities">Vedi tutte le attività <ChevronRight/></Link></Button></CardFooter></Card> }
function ProjectsStandalone() { const nearestProjects = [...projects].filter((project) => project.deadlineDate).sort((a, b) => { const aDeadline = getProjectDeadline(a.deadlineDate); const bDeadline = getProjectDeadline(b.deadlineDate); return aDeadline.order - bDeadline.order || a.deadlineDate.localeCompare(b.deadlineDate) }).slice(0, 3); return <Card className="flex h-full flex-col @xl/main:col-span-5"><CardHeader><div className="flex items-center justify-between gap-2"><CardTitle>Progetti in corso</CardTitle><Badge variant="secondary">{projects.length} progetti</Badge></div></CardHeader><CardContent className="flex-1 space-y-3">{nearestProjects.map((item,index) => { const deadline = getProjectDeadline(item.deadlineDate); return <div key={item.id}><Link href={`/projects/${item.id}`} aria-label={`Apri progetto ${item.name}`} className="block cursor-pointer rounded-md outline-none transition-colors hover:bg-muted/50 focus-visible:ring-2 focus-visible:ring-ring"><div className="p-1.5"><div className="flex flex-wrap items-center gap-x-3 gap-y-1"><p className="min-w-0 flex-1 text-sm font-medium">{item.name}</p><BadgeTone tone={deadline.tone}>{item.deadline} · {deadline.label}</BadgeTone></div><p className="mt-1 text-xs text-muted-foreground">{item.client}</p><div className="mt-2 flex items-center gap-2"><Progress aria-label={`${item.name}: avanzamento ${item.progress}%`} value={item.progress} className="[&_[data-slot=progress-indicator]]:bg-foreground"/><span className="text-xs font-medium text-foreground tabular-nums">{item.progress}%</span></div></div></Link>{index < nearestProjects.length - 1 && <Separator className="mt-3"/>}</div> })}</CardContent><CardFooter className="mt-auto"><Button asChild variant="link" size="sm" className="px-0"><Link href="/projects">Vedi tutti i progetti <ChevronRight/></Link></Button></CardFooter></Card> }
function ActiveClientsCard({metric}:{metric:typeof activeClientsFixtures[DashboardRange]}) { const current = metric.series.at(-1)?.value ?? 0; const previous = metric.series.at(-2)?.value ?? 0; const trend = getMetricTrend({metric:"revenue",currentValue:current,previousValue:previous}); return <Card className="flex h-full flex-col @xl/main:col-span-3"><CardHeader><CardTitle>Clienti attivi</CardTitle><CardDescription>Andamento del portafoglio clienti</CardDescription></CardHeader><CardContent className="flex-1"><div className="flex flex-wrap items-baseline gap-2"><span className="text-2xl font-semibold">{metric.value} clienti</span><BadgeTone tone={trend.variant}>{trend.label}</BadgeTone></div><p className="mt-1 text-xs text-muted-foreground">rispetto allo stesso periodo dell’anno precedente</p><MetricAreaChart label="Clienti attivi" token="chart-3" data={metric.series} kind="number" compact/></CardContent><CardFooter className="mt-auto"><Button asChild variant="link" size="sm" className="px-0"><Link href="/clients">Vedi tutti i clienti <ChevronRight/></Link></Button></CardFooter></Card> }
function OperationsCard(){return null}
function MissionDeadlines() {
 const icons = [CircleDollarSign, Trophy, CheckCircle2]
 const allDeadlines = dashboardDeadlines
 return <Card className="@xl/main:col-span-4">
  <CardHeader><CardTitle>Missione e scadenze</CardTitle><CardDescription>Obiettivi e prossimi impegni</CardDescription></CardHeader>
  <CardContent>
   <Tabs defaultValue="mission">
    <TabsList className="grid w-full grid-cols-2" aria-label="Missione e scadenze">
     <TabsTrigger value="mission">Missione del mese</TabsTrigger>
     <TabsTrigger value="deadlines">Scadenze clienti</TabsTrigger>
    </TabsList>
    <TabsContent value="mission" className="space-y-3 pt-3">
       <div className="flex items-end gap-2"><span className="text-3xl font-semibold text-foreground">{monthlyMission.completionPercentage}%</span></div>
       <Progress aria-label={`Missione del mese: ${monthlyMission.completionPercentage}%`} value={monthlyMission.completionPercentage}/>
       <span className="text-xs text-muted-foreground">{monthlyMission.completedObjectives} obiettivi completati su {monthlyMission.totalObjectives}</span>
       <p className="text-xs text-muted-foreground">{monthlyMission.daysRemaining} giorni rimanenti · Prossimo obiettivo: {euro.format(monthlyMission.nextRevenueObjective)}</p>
       <p className="text-sm text-muted-foreground">Hai raggiunto il {monthlyMission.completionPercentage}% della missione mensile. Mancano {monthlyMission.totalObjectives - monthlyMission.completedObjectives} obiettivi al prossimo traguardo.</p>
     <Separator/>
       {monthlyMission.objectives.map((objective, index) => { const Icon = icons[index]; const progress = objectiveProgress(objective.current, objective.target); return <div key={objective.id} className="space-y-1.5"><div className="flex flex-wrap items-center gap-2 text-sm"><Icon className="size-3.5 shrink-0 text-muted-foreground"/><span className="min-w-0 flex-1 truncate">{objective.label}</span><span className="ml-auto shrink-0 text-xs font-medium tabular-nums text-muted-foreground">{objectiveValue(objective)}</span></div><div className="flex items-center gap-2"><Progress aria-label={`${objective.label}: ${progress}%`} value={progress}/><span className="text-xs font-medium tabular-nums text-muted-foreground">{progress}%</span></div></div> })}
     <Button variant="link" size="sm" className="px-0">Vedi tutti gli obiettivi <ChevronRight/></Button>
    </TabsContent>
    <TabsContent value="deadlines" className="space-y-3 pt-3">
     {allDeadlines.map((deadline, index) => <div key={deadline.id}><div className="flex items-center gap-3"><Badge variant="outline" className="shrink-0">{deadline.date}</Badge><div className="min-w-0 flex-1"><p className="text-sm font-medium">{deadline.title}</p><p className="text-xs text-muted-foreground">{deadline.detail} · Responsabile AR</p></div><BadgeTone tone={deadline.tone}>{deadline.status}</BadgeTone></div>{index < allDeadlines.length - 1 && <Separator className="mt-3"/>}</div>)}
     <Button variant="link" size="sm" className="px-0">Vedi tutte le scadenze <ChevronRight/></Button>
    </TabsContent>
   </Tabs>
  </CardContent>
 </Card>
}

function OperationsOnly() {
 const allPriorities = priorities.concat([
  { id: "activity-approve-creatives", title: "Approvazione creatività", detail: "Green Future", time: "17:30", initials: "GF", tone: "success" as StatusTone },
  { id: "activity-report-performance", title: "Report performance", detail: "Meta Ads", time: "09:30", initials: "MA", tone: "neutral" as StatusTone },
 ])
 const allProjects = projects.concat([{ id: "project-legacy-campaign", name: "Legacy Campaign", client: "Legacy", progress: 64, deadline: "18 set", deadlineDate: "2026-09-18", state: "Vicino", tone: "warning" as const }])
 return <Card>
  <CardHeader><CardTitle>Operatività</CardTitle><CardDescription>Attività prioritarie e progetti in corso</CardDescription></CardHeader>
  <CardContent>
   <Tabs defaultValue="priorities">
    <TabsList className="grid w-full grid-cols-2" aria-label="Operatività">
     <TabsTrigger value="priorities">Priorità di oggi</TabsTrigger>
     <TabsTrigger value="projects">Progetti in corso</TabsTrigger>
    </TabsList>
    <TabsContent value="priorities" className="space-y-3 pt-3">
     {allPriorities.map((priority, index) => <div key={priority.title}><div className="flex items-center gap-3"><ListTodo className="size-4 shrink-0 text-muted-foreground"/><div className="min-w-0 flex-1"><p className="text-sm font-medium">{priority.title}</p><p className="text-xs text-muted-foreground">{priority.detail} · Attività operativa</p></div><BadgeTone tone={priority.tone}>{priority.tone === "destructive" ? "Urgente" : priority.tone === "warning" ? "Alta" : "Normale"}</BadgeTone><span className="text-xs tabular-nums">{priority.time}</span><Avatar size="sm"><AvatarFallback>{priority.initials}</AvatarFallback></Avatar></div>{index < allPriorities.length - 1 && <Separator className="mt-3"/>}</div>)}
     <Button variant="link" size="sm" className="px-0">Vedi tutte le attività <ChevronRight/></Button>
    </TabsContent>
    <TabsContent value="projects" className="space-y-3 pt-3">
     {allProjects.map((project, index) => <div key={project.name}><div className="grid gap-2 @md/main:grid-cols-[1fr_1.5fr_auto]"><div><p className="text-sm font-medium">{project.name}</p><p className="text-xs text-muted-foreground">Responsabile AR</p></div><Progress value={project.progress}/><div className="flex items-center gap-2"><span className="text-xs">{project.progress}%</span><BadgeTone tone={project.tone}>{project.deadline}</BadgeTone></div></div>{index < allProjects.length - 1 && <Separator className="mt-3"/>}</div>)}
     <Button variant="link" size="sm" className="px-0">Vedi tutti i progetti <ChevronRight/></Button>
    </TabsContent>
   </Tabs>
  </CardContent>
 </Card>
}

function SummaryRow({ data, range, custom, onRangeChange, onCustom }: { data: typeof overviewRangeFixtures["30d"]; range: DashboardRange | "year"; custom: boolean; onRangeChange: (range: DashboardRange | "year") => void; onCustom: () => void }) {
 const [activeMetric, setActiveMetric] = useState<"revenue" | "expenses" | "profit">("revenue"); const entries = [{ id: "revenue" as const, label: "Fatturato", metric: data.metrics[0], icon: TrendingUp, colors: "border-emerald-500/30 bg-emerald-500/5 text-emerald-700 dark:text-emerald-300" }, { id: "expenses" as const, label: "Spese", metric: data.metrics[1], icon: ReceiptText, colors: "border-red-500/30 bg-red-500/5 text-red-700 dark:text-red-300" }, { id: "profit" as const, label: "Utile", metric: data.metrics[2], icon: BadgeEuro, colors: "border-violet-500/30 bg-violet-500/5 text-violet-700 dark:text-violet-300" }]
 return <section className="grid items-stretch gap-4 @xl/main:grid-cols-12"><Card className="min-w-0 @xl/main:col-span-8"><CardHeader className="gap-3 pb-2"><div className="flex flex-col gap-3 @2xl/main:flex-row @2xl/main:items-start @2xl/main:justify-between"><div><CardTitle>Andamento economico</CardTitle><CardDescription>Anno corrente, confronto precedente e dettaglio delle tre metriche.</CardDescription></div><div className="flex max-w-full gap-1 overflow-x-auto pb-1"><Select value={range} onValueChange={(value) => onRangeChange(value as DashboardRange | "year")}><SelectTrigger className="w-40 shrink-0" aria-label="Periodo andamento economico"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="7d">Oggi</SelectItem><SelectItem value="30d">Questo mese</SelectItem><SelectItem value="90d">Mese scorso</SelectItem><SelectItem value="year">Anno corrente</SelectItem></SelectContent></Select><Popover><PopoverTrigger asChild><Button variant="outline" className="shrink-0">{custom ? "01 ago – 18 ago" : "Personalizzato"}</Button></PopoverTrigger><PopoverContent align="end" className="w-auto p-3"><Calendar mode="range" numberOfMonths={1}/><div className="mt-3 flex justify-end gap-2"><Button variant="ghost" size="sm">Annulla</Button><Button size="sm" onClick={onCustom}>Applica</Button></div></PopoverContent></Popover></div></div><div className="flex snap-x gap-2 overflow-x-auto pb-1 sm:grid sm:grid-cols-3">{entries.map((entry) => { const Icon = entry.icon; const selected = activeMetric === entry.id; return <button key={entry.id} type="button" onClick={() => setActiveMetric(entry.id)} aria-pressed={selected} className={`min-w-[190px] snap-start rounded-lg border p-3 text-left transition-colors sm:min-w-0 ${selected ? entry.colors : "bg-card hover:bg-muted/40"}`}><div className="flex items-start justify-between gap-2"><span className="text-xs font-medium">{entry.label}</span><Icon className="size-4" /></div><p className="mt-1 text-xl font-semibold tabular-nums">{entry.metric.value}</p><p className="text-xs text-muted-foreground">{entry.metric.change} · {entry.metric.comparison}</p></button> })}</div><div className="flex flex-wrap items-center gap-x-4 gap-y-1 text-xs text-muted-foreground"><span className="flex items-center gap-1.5"><i className="size-2 rounded-full bg-emerald-500" />Fatturato</span><span className="flex items-center gap-1.5"><i className="size-2 rounded-full bg-red-500" />Spese</span><span className="flex items-center gap-1.5"><i className="size-2 rounded-full bg-violet-500" />Utile</span><span className="flex items-center gap-1.5"><i className="h-0 w-5 border-t border-dashed border-muted-foreground" />Anno precedente</span></div></CardHeader><CardContent className="px-2 pb-2 sm:px-4"><FinancialSummaryChart metrics={data.metrics} activeMetric={activeMetric}/></CardContent></Card><MissionDeadlines/></section>
}
function ProjectsAndDeadlines(){return null}
function PrioritiesCard(){return <Card className="@xl/main:col-span-4"><CardHeader><div className="flex justify-between gap-2"><div><CardTitle>Priorità di oggi</CardTitle><CardDescription>Le attività da non perdere</CardDescription></div><Badge variant="secondary">4 attività</Badge></div></CardHeader><CardContent className="space-y-3">{priorities.concat([{id:"activity-approve-creatives",title:"Approvazione creatività",detail:"Green Future",time:"17:30",initials:"GF",tone:"success" as const}]).map((x,i)=><div key={x.title}><div className="flex items-center gap-2"><ListTodo className="size-4 shrink-0 text-muted-foreground"/><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{x.title}</p><p className="text-xs text-muted-foreground">{x.detail}</p></div><BadgeTone tone={x.tone}>{x.tone==="destructive"?"Urgente":x.tone==="warning"?"Alta":"Normale"}</BadgeTone><span className="text-xs tabular-nums">{x.time}</span><Avatar size="sm"><AvatarFallback>{x.initials}</AvatarFallback></Avatar></div>{i<3&&<Separator className="mt-3"/>}</div>)}<Button variant="link" size="sm" className="px-0">Vedi tutte le attività <ChevronRight/></Button></CardContent></Card>}
function MissionCompact(){const icons=[CircleDollarSign,Trophy,CheckCircle2];return <Card className="@xl/main:col-span-4"><CardHeader><CardTitle>Missione del mese</CardTitle><CardDescription>Obiettivi principali di agosto</CardDescription></CardHeader><CardContent className="space-y-3"><div className="flex items-end gap-2"><span className="text-3xl font-semibold">72%</span><Badge variant="secondary">3 di 5</Badge></div><Progress value={72}/><p className="text-xs text-muted-foreground">13 giorni rimanenti · Prossimo: € 35.000</p><p className="text-sm text-muted-foreground">Sei al 72%. Mancano 2 obiettivi al prossimo traguardo.</p><Separator/>{missionObjectives.slice(0,3).map((o,i)=>{const Icon=icons[i];return <Tooltip key={o.label}><TooltipTrigger asChild><div className="space-y-1.5"><div className="flex items-center gap-2 text-sm"><Icon className="size-3.5 text-muted-foreground"/><span className="min-w-0 flex-1 truncate">{o.label}</span><Status value={o.status}/></div><div className="flex gap-2"><Progress value={o.progress}/><span className="text-xs">{o.progress}%</span></div></div></TooltipTrigger><TooltipContent>{o.current} su {o.target}</TooltipContent></Tooltip>})}</CardContent><CardFooter><Button variant="link" size="sm" className="px-0">Vedi tutti gli obiettivi <ChevronRight/></Button></CardFooter></Card>}
