import sharp from 'sharp';
import { TenantSiteProposalsBrandService } from './tenant-site-proposals-brand.service';
describe('proposal brand processing',()=>{
  const fetcher={fetchImage:jest.fn()} as any;const service=new TenantSiteProposalsBrandService(fetcher);let logo:Buffer;
  beforeAll(async()=>{logo=await sharp({create:{width:180,height:80,channels:4,background:{r:20,g:110,b:170,alpha:.8}}}).png().toBuffer()});
  it('creates bounded default and light data URIs',async()=>{const result=await service.processLogo(logo);expect(result.logoDefault).toMatch(/^data:image\/webp;base64,/);expect(result.logoLight).toMatch(/^data:image\/webp;base64,/);expect(Buffer.from(String(result.logoDefault).split(',')[1],'base64').length).toBeLessThanOrEqual(150*1024)});
  it('keeps alpha in the light logo',async()=>{const result=await service.processLogo(logo);const metadata=await sharp(Buffer.from(String(result.logoLight).split(',')[1],'base64')).metadata();expect(metadata.hasAlpha).toBe(true);expect(metadata.width).toBeLessThanOrEqual(800);expect(metadata.height).toBeLessThanOrEqual(400)});
  it('extracts a dominant palette with contrast',async()=>{const palette=await service.paletteFromImage(logo) as any;expect(palette.primary).toMatch(/^#[0-9a-f]{6}$/);expect(['#ffffff','#17211e']).toContain(palette.textOnPrimary);expect(palette.primaryHover).not.toBe(palette.primary)});
  it('ignores unsafe SVG script content while rasterizing',async()=>{const svg=Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" width="100" height="40"><script>alert(1)</script><rect width="100" height="40" fill="#336699"/></svg>');await expect(service.processLogo(svg)).resolves.toMatchObject({logoDefault:expect.stringMatching(/^data:image\/webp;base64,/)});});
  it('falls back to text when candidates fail',async()=>{fetcher.fetchImage.mockRejectedValue(new Error('no'));const result=await service.extract({logoCandidates:['https://example.com/logo.png'],colors:['#123456'],sourceUrl:'',finalUrl:'',title:'',description:'',headings:[],paragraphs:[],navigation:[],ctas:[],emails:[],phones:[],social:{},imageCandidates:[],text:''});expect(result.logoDefault).toBe('');expect(result.logoSource).toBe('text');expect((result.warnings as string[]).length).toBeGreaterThan(0)});
});
