import { ConflictException } from '@nestjs/common';
import { ProposalAiUnavailableError } from './tenant-site-proposals-ai.service';
import { TenantSiteProposalsPersonalizationService } from './tenant-site-proposals-personalization.service';
import { TenantSiteProposalsTemplateService } from './tenant-site-proposals-template.service';
jest.mock('./tenant-site-proposals-schema',()=>({ensureDoflowSiteProposalTables:jest.fn().mockResolvedValue(undefined)}));
const id='550e8400-e29b-41d4-a716-446655440000',runId='660e8400-e29b-41d4-a716-446655440000';
function proposal(version='2.0.0'){return {id,display_name:'Studio Demo',template_slug:'colsova',template_version:version,status:'draft',current_version:1,source_data:{businessName:'Studio Demo',city:'Roma',category:'studio professionale',services:['A','B','C'],brands:[],extra:{}},site_config:{}}}
function setup(queryResults:any[]=[]){const query=jest.fn();queryResults.forEach(value=>query.mockResolvedValueOnce(value));const runnerQuery=jest.fn().mockResolvedValueOnce([{id,template_version:'2.0.0'}]).mockResolvedValue([]);const runner={connect:jest.fn(),startTransaction:jest.fn(function(){(this as any).isTransactionActive=true}),query:runnerQuery,commitTransaction:jest.fn(function(){(this as any).isTransactionActive=false}),rollbackTransaction:jest.fn(function(){(this as any).isTransactionActive=false}),release:jest.fn(),isTransactionActive:false};const ds={query,createQueryRunner:jest.fn(()=>runner)} as any;const fetcher={fetchHomepage:jest.fn()} as any,extractor={extract:jest.fn()} as any,brand={extract:jest.fn()} as any;const images={resolveImages:jest.fn().mockResolvedValue({images:{hero:{src:'https://images.unsplash.com/hero',alt:'Hero',objectPosition:'center',sourceMethod:'catalog'},consultation:{src:'https://images.unsplash.com/consultation',alt:'Consultation',objectPosition:'center',sourceMethod:'catalog'},feature:{src:'https://images.unsplash.com/feature',alt:'Feature',objectPosition:'center',sourceMethod:'catalog'}},warnings:[]})} as any;const ai={configuration:jest.fn(()=>({model:'gemini-3.5-flash'})),generate:jest.fn()} as any;const service=new TenantSiteProposalsPersonalizationService(ds,fetcher,extractor,brand,images,ai,new TenantSiteProposalsTemplateService(),{user:{id,role:'manager'},tenant:{schemaName:'doflow'}});return {service,query,runner,runnerQuery,ai,fetcher,brand,images};}
describe('proposal personalization coordinator',()=>{
  it('requires explicit upgrade for legacy proposals',async()=>{const x=setup([[proposal('1.0.0')]]);await expect(x.service.personalize(id,{})).rejects.toThrow('Aggiorna prima');expect(x.ai.generate).not.toHaveBeenCalled()});
  it('returns a cached snapshot without Gemini or a new version',async()=>{const cached={id:runId,status:'fallback'};const x=setup([[proposal()],[],[],[cached]]);await expect(x.service.personalize(id,{})).resolves.toMatchObject({cached:true,status:'fallback'});expect(x.ai.generate).not.toHaveBeenCalled();expect(x.runner.query).not.toHaveBeenCalled()});
  it('applies deterministic fallback and commits one version',async()=>{const x=setup([[proposal()],[],[],[{id:runId}],[/* update running */]]);x.ai.generate.mockRejectedValue(new ProposalAiUnavailableError('missing_key'));const result=await x.service.personalize(id,{force:true});expect(result).toMatchObject({cached:false,status:'fallback',provider:'local'});expect(x.runner.commitTransaction).toHaveBeenCalled();expect(x.runnerQuery.mock.calls.some(([sql])=>String(sql).includes('site_proposal_versions'))).toBe(true);expect(x.runnerQuery.mock.calls.some(([sql,args])=>String(sql).includes('site_proposal_activity')&&args[1]==='PROPOSAL_PERSONALIZATION_FALLBACK')).toBe(true)});
  it('persists resolved image methods and warnings before Gemini fallback',async()=>{const x=setup([[proposal()],[],[],[{id:runId}],[]]);x.images.resolveImages.mockResolvedValue({images:{hero:{src:'https://example.com/hero.jpg',alt:'Hero',objectPosition:'center',sourceMethod:'website'},consultation:{src:'https://images.unsplash.com/c1',alt:'C',objectPosition:'center',sourceMethod:'catalog'},feature:{src:'https://images.unsplash.com/f1',alt:'F',objectPosition:'center',sourceMethod:'catalog_fallback'}},warnings:['warning catalogo']});x.ai.generate.mockRejectedValue(new ProposalAiUnavailableError('missing_key'));await x.service.personalize(id,{force:true});const update=x.runnerQuery.mock.calls.find(([sql])=>String(sql).includes('SET template_version'))?.[1];const config=JSON.parse(update[0]);expect(config.images.hero.sourceMethod).toBe('website');expect(config.images.consultation.src).toBeTruthy();expect(config.images.feature.src).toBeTruthy();expect(config.personalization.warnings).toContain('warning catalogo')});
  it('uses validated Gemini output and marks completed',async()=>{const x=setup([[proposal()],[],[],[{id:runId}],[]]);x.ai.generate.mockResolvedValue({model:'gemini-test',output:{analysis:{summary:'Sintesi',strengths:[],improvementAreas:[],opportunities:[],whyDoflow:[],requiresManualReview:true},content:{hero:{},approach:{},services:[{title:'A',description:'a'},{title:'B',description:'b'},{title:'C',description:'c'}],benefits:{},trustItems:Array.from({length:6},(_,i)=>({title:`T${i}`,description:'d'})),faq:Array.from({length:6},(_,i)=>({question:`Q${i}`,answer:'a'})),contact:{},footer:{}},seo:{title:'Titolo',description:'Descrizione'},email:{subject:'Oggetto',body:'Corpo [LINK_DEMO]'}}});const result=await x.service.personalize(id,{force:true});expect(result).toMatchObject({status:'completed',provider:'gemini'});expect(x.runnerQuery.mock.calls.some(([sql,args])=>String(sql).includes('site_proposal_activity')&&args[1]==='PROPOSAL_PERSONALIZATION_COMPLETED')).toBe(true)});
  it('marks the run failed and never applies a partial config on total error',async()=>{const x=setup([[proposal()],[],[],[{id:runId}],[],[]]);x.ai.generate.mockRejectedValue(new Error('unexpected'));await expect(x.service.personalize(id,{force:true})).rejects.toThrow('unexpected');expect(x.runner.query).not.toHaveBeenCalled();expect(x.query.mock.calls.some(([sql,args])=>String(sql).includes("status='failed'")&&args[1]===runId)).toBe(true)});
  it('blocks an in-process duplicate and always releases the lock',async()=>{const x=setup();(x.service as any).locks.add(id);await expect(x.service.personalize(id,{})).rejects.toThrow('Personalizzazione già in corso');(x.service as any).locks.delete(id);const y=setup([[proposal('1.0.0')]]);await expect(y.service.personalize(id,{})).rejects.toBeInstanceOf(ConflictException);expect((y.service as any).locks.has(id)).toBe(false)});
});
