"use client";

import { useEffect, useMemo, useState } from "react";
import { Check, Clipboard, RotateCcw } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "@/components/ui/collapsible";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { CommercialSectionCard } from "@/components/tenant-commercial/commercial-ui";
import type { JsonObject, SiteConfig } from "@/lib/tenant-site-proposals-api";
import { copyJson, getPath, hasUnsafePrototype, isSafeRoute, setPath, textLimit } from "./site-proposal-utils";

function stringValue(value: unknown) { return typeof value === "string" || typeof value === "number" ? String(value) : ""; }
function Field({ config, path, label, onChange, multiline = false, readOnly = false }: { config: SiteConfig; path: string; label: string; onChange: (path: string, value: string) => void; multiline?: boolean; readOnly?: boolean }) {
  const value = stringValue(getPath(config, path)); const limit = textLimit(config, path); const counter = limit ? <span className={value.length > limit ? "text-rose-600" : value.length > limit * .9 ? "text-amber-600" : "text-slate-400"}>{value.length}/{limit}</span> : null;
  return <div><Label htmlFor={path}>{label}</Label>{multiline ? <Textarea id={path} readOnly={readOnly} value={value} className="mt-1 min-h-24" onChange={(event) => onChange(path, event.target.value)} /> : <Input id={path} readOnly={readOnly} value={value} className="mt-1 h-10" onChange={(event) => onChange(path, event.target.value)} />}{counter ? <p className="mt-1 text-right text-xs">{counter}</p> : null}</div>;
}
function ArrayTextField({ value, label, onChange, limit }: { value: string; label: string; onChange: (value: string) => void; limit?: number }) { return <div><Label>{label}</Label><Input className="mt-1 h-10" value={value} onChange={(event) => onChange(event.target.value)} />{limit ? <p className="mt-1 text-right text-xs text-slate-400">{value.length}/{limit}</p> : null}</div>; }

export function SiteProposalConfigEditor({ config, onChange }: { config: SiteConfig; onChange: (next: SiteConfig) => void }) {
  const [jsonText, setJsonText] = useState(() => JSON.stringify(config, null, 2)); const [jsonError, setJsonError] = useState<string | null>(null);
  useEffect(() => { setJsonText(JSON.stringify(config, null, 2)); }, [config]);
  const change = (path: string, value: string) => onChange(setPath(config, path, value));
  const content = config.content as JsonObject; const treatments = ((content.treatments as JsonObject)?.cards || []) as JsonObject[]; const products = (content.products as JsonObject) || {}; const reviews = ((content.reviews as JsonObject)?.items || []) as JsonObject[]; const faqs = ((content.faq as JsonObject)?.items || []) as JsonObject[];
  const applyJson = () => { try { const parsed: unknown = JSON.parse(jsonText); if (!parsed || typeof parsed !== "object" || Array.isArray(parsed) || hasUnsafePrototype(parsed)) throw new Error("Il JSON deve essere un oggetto senza chiavi non consentite."); onChange(parsed as SiteConfig); setJsonError(null); toast.success("JSON applicato al draft locale."); } catch (error) { setJsonError(error instanceof Error ? error.message : "JSON non valido."); } };
  const copy = async () => { try { await navigator.clipboard.writeText(JSON.stringify(config, null, 2)); toast.success("SiteConfig copiato."); } catch { toast.error("Copia non disponibile."); } };
  const updateArray = (path: string, index: number, field: string, value: string) => { const list = copyJson(getPath(config, path) as JsonObject[]); list[index] = { ...list[index], [field]: value }; onChange(setPath(config, path, list)); };
  const updatePoint = (index: number, value: string) => { const list = copyJson(products.points as string[]); list[index] = value; onChange(setPath(config, "content.products.points", list)); };
  const template = config.template as JsonObject; const contract = config.editingContract as JsonObject; const routing = config.routing as JsonObject;
  return <div className="space-y-5"><CommercialSectionCard title="Identità"><div className="grid gap-4 md:grid-cols-2"><Field config={config} path="brand.name" label="Nome" onChange={change} /><Field config={config} path="brand.professionalTitle" label="Qualifica" onChange={change} /><Field config={config} path="brand.descriptor" label="Descrittore" onChange={change} /><Field config={config} path="brand.initials" label="Iniziali" onChange={change} /></div></CommercialSectionCard>
    <CommercialSectionCard title="Attività"><div className="grid gap-4 md:grid-cols-2"><Field config={config} path="business.city" label="Città" onChange={(path, value) => { const before = stringValue(getPath(config, "business.city")); const previousSlug = stringValue(getPath(config, "business.citySlug")); const generated = before.toLowerCase().normalize("NFKD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, ""); let next = setPath(config, path, value); if (!previousSlug || previousSlug === generated) next = setPath(next, "business.citySlug", value.toLowerCase().normalize("NFKD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "")); onChange(next); }} /><Field config={config} path="business.citySlug" label="City slug" onChange={change} /><Field config={config} path="business.address" label="Indirizzo" onChange={change} /><Field config={config} path="business.phoneDisplay" label="Telefono" onChange={change} /><Field config={config} path="business.phoneHref" label="Telefono (href)" onChange={change} /><Field config={config} path="business.email" label="Email" onChange={change} /><Field config={config} path="business.mapUrl" label="URL mappa" onChange={change} /><Field config={config} path="business.copyrightYear" label="Anno copyright" onChange={change} /><Field config={config} path="business.developerCredit" label="Crediti" onChange={change} /></div></CommercialSectionCard>
    <CommercialSectionCard title="Brief e SEO"><div className="grid gap-4 md:grid-cols-2"><Field config={config} path="sourceWebsite.url" label="Sito attuale" onChange={change} /><Field config={config} path="sourceWebsite.primaryGoal" label="Obiettivo" onChange={change} /><Field config={config} path="sourceWebsite.overview" label="Panoramica" onChange={change} multiline /><Field config={config} path="sourceWebsite.targetAudience" label="Pubblico" onChange={change} multiline /><Field config={config} path="sourceWebsite.toneOfVoice" label="Tono di voce" onChange={change} multiline /><Field config={config} path="sourceWebsite.notes" label="Note" onChange={change} multiline /><Field config={config} path="seo.title" label="Titolo SEO" onChange={change} /><Field config={config} path="seo.description" label="Descrizione SEO" onChange={change} multiline /></div></CommercialSectionCard>
    <CommercialSectionCard title="Contenuti"><div className="space-y-4"><div className="grid gap-4 md:grid-cols-2"><Field config={config} path="content.navigation.home" label="Navigazione: Home" onChange={change} /><Field config={config} path="content.navigation.contacts" label="Navigazione: Contatti" onChange={change} /><Field config={config} path="content.hero.eyebrow" label="Hero eyebrow" onChange={change} /><Field config={config} path="content.hero.titleLine" label="Hero titolo" onChange={change} /><Field config={config} path="content.hero.titleEmphasis" label="Hero enfasi" onChange={change} /><Field config={config} path="content.hero.description" label="Hero descrizione" onChange={change} multiline /><Field config={config} path="content.consultation.titleLine" label="Consulenza titolo" onChange={change} /><Field config={config} path="content.consultation.titleEmphasis" label="Consulenza enfasi" onChange={change} /><Field config={config} path="content.consultation.paragraph1" label="Consulenza paragrafo 1" onChange={change} multiline /><Field config={config} path="content.consultation.paragraph2" label="Consulenza paragrafo 2" onChange={change} multiline /></div>
      <h3 className="pt-2 font-semibold text-slate-900">Trattamenti (3)</h3><div className="grid gap-3 lg:grid-cols-3">{treatments.map((item, index) => <div key={index} className="rounded-xl border border-slate-200 p-3"><ArrayTextField label="Titolo" value={stringValue(item.title)} onChange={(value) => updateArray("content.treatments.cards", index, "title", value)} /><div className="mt-3"><Label>Descrizione</Label><Textarea className="mt-1" value={stringValue(item.description)} onChange={(event) => updateArray("content.treatments.cards", index, "description", event.target.value)} /></div><ArrayTextField label="CTA" value={stringValue(item.cta)} onChange={(value) => updateArray("content.treatments.cards", index, "cta", value)} /></div>)}</div>
      <h3 className="pt-2 font-semibold text-slate-900">Prodotti (3 punti)</h3><div className="grid gap-3 md:grid-cols-3">{((products.points || []) as string[]).map((point, index) => <ArrayTextField key={index} label={`Punto ${index + 1}`} value={point} onChange={(value) => updatePoint(index, value)} />)}</div>
      <h3 className="pt-2 font-semibold text-slate-900">Recensioni (6)</h3><p className="text-sm text-amber-700">Le recensioni sono placeholder finché non vengono verificate manualmente.</p><div className="grid gap-3 lg:grid-cols-2">{reviews.map((item, index) => <div key={index} className="rounded-xl border border-slate-200 p-3"><div className="grid gap-3 sm:grid-cols-2"><ArrayTextField label="Nome" value={stringValue(item.name)} onChange={(value) => updateArray("content.reviews.items", index, "name", value)} /><ArrayTextField label="Titolo" value={stringValue(item.title)} onChange={(value) => updateArray("content.reviews.items", index, "title", value)} /></div><div className="mt-3"><Label>Testo</Label><Textarea className="mt-1" value={stringValue(item.text)} onChange={(event) => updateArray("content.reviews.items", index, "text", event.target.value)} /></div></div>)}</div>
      <h3 className="pt-2 font-semibold text-slate-900">FAQ (6)</h3><div className="grid gap-3 lg:grid-cols-2">{faqs.map((item, index) => <div key={index} className="rounded-xl border border-slate-200 p-3"><ArrayTextField label="Domanda" value={stringValue(item.question)} onChange={(value) => updateArray("content.faq.items", index, "question", value)} /><div className="mt-3"><Label>Risposta</Label><Textarea className="mt-1" value={stringValue(item.answer)} onChange={(event) => updateArray("content.faq.items", index, "answer", event.target.value)} /></div></div>)}</div></div></CommercialSectionCard>
    <CommercialSectionCard title="Palette"><div className="overflow-x-auto"><table className="w-full min-w-[640px] text-sm"><thead><tr className="border-b text-left text-slate-500"><th className="p-2">Campione</th><th className="p-2">Variabile</th><th className="p-2">Ruolo</th><th className="p-2">Valore</th></tr></thead><tbody>{config.palette.map((color, index) => <tr key={color.variable} className="border-b"><td className="p-2"><span className="block h-7 w-7 rounded border" style={{ background: color.value }} /></td><td className="p-2 font-mono text-xs">{color.variable}</td><td className="p-2 text-slate-600">{color.role}</td><td className="p-2"><div className="flex gap-2">{/^#[0-9a-f]{6}$/i.test(color.value) ? <input aria-label={`Colore ${color.variable}`} type="color" value={color.value} onChange={(event) => { const palette = copyJson(config.palette); palette[index].value = event.target.value; onChange({ ...config, palette }); }} /> : null}<Input value={color.value} onChange={(event) => { const palette = copyJson(config.palette); palette[index].value = event.target.value; onChange({ ...config, palette }); }} /></div></td></tr>)}</tbody></table></div></CommercialSectionCard>
    <CommercialSectionCard title="Immagini e prompt"><div className="grid gap-4 lg:grid-cols-2">{Object.entries(config.images).map(([slot, image]) => <div key={slot} className="rounded-xl border border-slate-200 p-4"><div className="flex items-center justify-between gap-3"><h3 className="font-semibold text-slate-900">{String(image.placeholderLabel || slot)}</h3><span className="text-xs text-slate-500">{String(image.recommendedSize || "")}</span></div>{image.src ? <img className="mt-3 h-36 w-full rounded-lg object-cover" src={String(image.src)} alt={String(image.alt || slot)} /> : <div className="mt-3 flex h-24 items-center justify-center rounded-lg bg-slate-100 text-xs text-slate-500">Placeholder {slot}</div>}<div className="mt-3 grid gap-3"><ArrayTextField label="URL immagine" value={stringValue(image.src)} onChange={(value) => onChange(setPath(config, `images.${slot}.src`, value))} /><ArrayTextField label="Alt" value={stringValue(image.alt)} onChange={(value) => onChange(setPath(config, `images.${slot}.alt`, value))} /><ArrayTextField label="Posizione" value={stringValue(image.objectPosition)} onChange={(value) => onChange(setPath(config, `images.${slot}.objectPosition`, value))} /><div><Label>Prompt</Label><Textarea className="mt-1" value={stringValue(image.prompt)} onChange={(event) => onChange(setPath(config, `images.${slot}.prompt`, event.target.value))} /></div><div className="flex gap-2"><Button type="button" size="sm" variant="outline" onClick={() => onChange(setPath(config, `images.${slot}.src`, ""))}>Usa placeholder</Button><Button type="button" size="sm" variant="outline" onClick={() => navigator.clipboard.writeText(stringValue(image.prompt)).then(() => toast.success("Prompt copiato.")).catch(() => toast.error("Copia non disponibile."))}><Clipboard className="mr-1 h-3.5 w-3.5" />Copia prompt</Button></div></div></div>)}</div></CommercialSectionCard>
    <CommercialSectionCard title="Route e reindirizzamenti"><div className="grid gap-4 lg:grid-cols-2"><div><Field config={config} path="routing.baseUrl" label="Base URL" onChange={change} /><p className="mt-3 text-sm text-slate-600">Anteprima locale: <strong>{String(routing.localPreviewMode) === "true" ? "attiva" : "attiva"}</strong></p><div className="mt-4 space-y-3">{Object.entries((routing.paths || {}) as JsonObject).map(([key, value]) => <div key={key}><Label htmlFor={`route-${key}`}>{key}</Label><Input id={`route-${key}`} className="mt-1" value={stringValue(value)} onChange={(event) => { if (!isSafeRoute(event.target.value)) { toast.error("Route non sicura."); return; } onChange(setPath(config, `routing.paths.${key}`, event.target.value)); }} /></div>)}</div></div><div><h3 className="text-sm font-semibold text-slate-900">Etichette route</h3><p className="mt-1 text-sm text-slate-500">Sono mostrate in sola lettura perché il renderer del template le protegge.</p><div className="mt-4 space-y-3">{Object.entries((routing.labels || {}) as JsonObject).map(([key, value]) => <Field key={key} config={config} path={`routing.labels.${key}`} label={key} onChange={change} readOnly />)}</div></div></div></CommercialSectionCard>
    <CommercialSectionCard title="Contratto template"><div className="grid gap-3 text-sm sm:grid-cols-2"><p>Nome: {String(template.name)}</p><p>Versione: {String(template.templateVersion)}</p><p>Schema: {String(template.schemaVersion)}</p><p>Layout bloccato: {String(template.layoutLocked)}</p><p className="sm:col-span-2">Conteggi: {JSON.stringify(contract.fixedCounts)}</p><p className="sm:col-span-2">Limiti testo: {Object.keys(config.textLimits).length} campi definiti</p></div></CommercialSectionCard>
    <Collapsible><CommercialSectionCard title="Configurazione JSON avanzata"><CollapsibleTrigger asChild><Button variant="outline">Apri editor JSON</Button></CollapsibleTrigger><CollapsibleContent className="mt-4 space-y-3"><p className="text-sm text-amber-700">Il layout del Tema Colsova è bloccato. Il backend rifiuterà modifiche a struttura, conteggi e chiavi protette.</p><Textarea value={jsonText} onChange={(event) => setJsonText(event.target.value)} className="min-h-[380px] font-mono text-xs" aria-label="Configurazione JSON avanzata" />{jsonError ? <p className="text-sm text-rose-600">{jsonError}</p> : null}<div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => void copy()}><Clipboard className="mr-2 h-4 w-4" />Copia SiteConfig</Button><Button variant="outline" onClick={() => setJsonText(JSON.stringify(config, null, 2))}><Check className="mr-2 h-4 w-4" />Formatta JSON</Button><Button variant="outline" onClick={() => setJsonText(JSON.stringify(config, null, 2))}><RotateCcw className="mr-2 h-4 w-4" />Ripristina dal draft</Button><Button onClick={applyJson}>Applica JSON al draft</Button></div></CollapsibleContent></CommercialSectionCard></Collapsible>
  </div>;
}
