"use client";

import { useEffect, useMemo, useState } from "react";
import { BriefcaseBusiness as Linkedin, Camera as Instagram, Copy, MessagesSquare as Facebook } from "lucide-react";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { CommercialSectionCard } from "@/components/tenant-commercial/commercial-ui";
import { commercialApi, type CommercialCompany, type CommercialContact, type CommercialLead, type CommercialOpportunity } from "@/lib/tenant-commercial-api";
import type { JsonObject, SiteConfig } from "@/lib/tenant-site-proposals-api";
import { getErrorMessage, setPath } from "./site-proposal-utils";

type Links = { companyId?: string | null; contactId?: string | null; leadId?: string | null; opportunityId?: string | null };
const none="__none__";const safeSocial=(value:string)=>!value||(()=>{try{return new URL(value).protocol==="https:"}catch{return false}})();
function SocialField({config,path,label,icon,onChange}:{config:SiteConfig;path:string;label:string;icon:React.ReactNode;onChange:(next:SiteConfig)=>void}){const business=config.business as JsonObject;const key=path.split(".").pop()!;const current=String(business[key]||"");const valid=safeSocial(current);return <div><Label htmlFor={path}>{label}</Label><div className="mt-1 flex gap-2"><span className="grid h-10 w-10 place-items-center rounded-md border text-slate-500">{icon}</span><Input id={path} value={current} aria-invalid={!valid} placeholder={`https://${label.toLowerCase()}.com/...`} onChange={(e)=>onChange(setPath(config,path,e.target.value))}/>{valid&&current?<a href={current} target="_blank" rel="noopener noreferrer" className="grid h-10 place-items-center rounded-md border px-3 text-xs font-medium">Apri</a>:null}</div>{!valid?<p className="mt-1 text-xs text-rose-600">Inserisci un URL HTTPS valido.</p>:null}</div>}

export function SiteProposalCrmEditor({ config, links, onConfigChange, onLinksChange }: { config: SiteConfig; links: Links; onConfigChange: (next: SiteConfig) => void; onLinksChange: (next: Links) => void }) {
  const [companies,setCompanies]=useState<CommercialCompany[]>([]),[contacts,setContacts]=useState<CommercialContact[]>([]),[leads,setLeads]=useState<CommercialLead[]>([]),[opportunities,setOpportunities]=useState<CommercialOpportunity[]>([]);const [error,setError]=useState<string|null>(null),[copyOpen,setCopyOpen]=useState(false);
  useEffect(()=>{let active=true;Promise.all([commercialApi.companies({limit:100}),commercialApi.contacts({limit:100}),commercialApi.leads({limit:100}),commercialApi.opportunities({limit:100})]).then(([a,b,c,d])=>{if(active){setCompanies(a.items);setContacts(b.items);setLeads(c.items);setOpportunities(d.items)}}).catch(e=>active&&setError(getErrorMessage(e)));return()=>{active=false}},[]);
  const filteredContacts=useMemo(()=>links.companyId?contacts.filter(x=>x.company_id===links.companyId):contacts,[contacts,links.companyId]);const filteredLeads=useMemo(()=>links.companyId?leads.filter(x=>x.company_id===links.companyId):leads,[leads,links.companyId]);const filteredOpportunities=useMemo(()=>links.companyId||links.contactId?opportunities.filter(x=>(!links.companyId||x.company_id===links.companyId)&&(!links.contactId||x.contact_id===links.contactId)):opportunities,[opportunities,links.companyId,links.contactId]);const company=companies.find(x=>x.id===links.companyId);
  const select=(key:keyof Links,v:string)=>onLinksChange({...links,[key]:v===none?null:v});const apply=()=>{if(!company)return;let next=setPath(config,"brand.name",company.name);if(company.city)next=setPath(next,"business.city",company.city);if(company.address)next=setPath(next,"business.address",company.address);if(company.email)next=setPath(next,"business.email",company.email);if(company.phone)next=setPath(next,"business.phoneDisplay",company.phone);if(company.website)next=setPath(next,"sourceWebsite.url",company.website);onConfigChange(next);setCopyOpen(false)};
  const choices=[{key:"companyId",label:"Azienda",items:companies.map(x=>({id:x.id,label:x.name}))},{key:"contactId",label:"Contatto",items:filteredContacts.map(x=>({id:x.id,label:`${x.first_name} ${x.last_name||""}`}))},{key:"leadId",label:"Lead",items:filteredLeads.map(x=>({id:x.id,label:x.title}))},{key:"opportunityId",label:"Opportunità",items:filteredOpportunities.map(x=>({id:x.id,label:x.title}))}] as const;
  return <div className="space-y-5"><CommercialSectionCard title="Contatti del sito"><dl className="grid gap-3 text-sm sm:grid-cols-2">{[["Nome",(config.brand as JsonObject).name],["Città",(config.business as JsonObject).city],["Telefono",(config.business as JsonObject).phoneDisplay],["Email",(config.business as JsonObject).email],["Sito attuale",(config.sourceWebsite as JsonObject).url]].map(([label,v])=><div key={String(label)}><dt className="text-slate-500">{String(label)}</dt><dd>{String(v||"—")}</dd></div>)}</dl></CommercialSectionCard>
    <CommercialSectionCard title="Social pubblici"><div className="grid gap-4"><SocialField config={config} path="business.socialLinkedIn" label="LinkedIn" icon={<Linkedin className="h-4 w-4"/>} onChange={onConfigChange}/><SocialField config={config} path="business.socialInstagram" label="Instagram" icon={<Instagram className="h-4 w-4"/>} onChange={onConfigChange}/><SocialField config={config} path="business.socialFacebook" label="Facebook" icon={<Facebook className="h-4 w-4"/>} onChange={onConfigChange}/></div><p className="mt-3 text-xs text-slate-500">I valori manuali validi non vengono sovrascritti durante una normale rianalisi.</p></CommercialSectionCard>
    <CommercialSectionCard title="Collegamenti CRM">{error?<p className="mb-3 text-sm text-rose-600">{error}</p>:null}<div className="grid gap-4 md:grid-cols-2">{choices.map(choice=><div key={choice.key}><Label>{choice.label}</Label><Select value={links[choice.key]||none} onValueChange={v=>select(choice.key,v)}><SelectTrigger className="mt-1"><SelectValue/></SelectTrigger><SelectContent><SelectItem value={none}>Nessuno</SelectItem>{choice.items.map(item=><SelectItem key={item.id} value={item.id}>{item.label}</SelectItem>)}</SelectContent></Select></div>)}</div>{company?<Button variant="outline" className="mt-5" onClick={()=>setCopyOpen(true)}><Copy className="mr-2 h-4 w-4"/>Copia dati dal CRM</Button>:null}</CommercialSectionCard>
    <AlertDialog open={copyOpen} onOpenChange={setCopyOpen}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Copia dati dall’azienda CRM</AlertDialogTitle><AlertDialogDescription>Nome, città, indirizzo, email, telefono e sito sostituiranno i dati pubblici corrispondenti. I social manuali restano invariati.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Annulla</AlertDialogCancel><AlertDialogAction onClick={apply}>Copia dati</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div>;
}
