"use client";

import { useEffect, useState } from "react";
import { Clipboard, Settings2 } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "@/components/ui/collapsible";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { CommercialSectionCard } from "@/components/tenant-commercial/commercial-ui";
import type { JsonObject, SiteConfig } from "@/lib/tenant-site-proposals-api";
import { getPath, hasUnsafePrototype, setPath, textLimit } from "./site-proposal-utils";

const value = (input: unknown) => typeof input === "string" || typeof input === "number" ? String(input) : "";
function Field({ config, path, label, multiline, onChange }: { config: SiteConfig; path: string; label: string; multiline?: boolean; onChange: (next: SiteConfig) => void }) { const current=value(getPath(config,path));const limit=textLimit(config,path);return <div><Label htmlFor={path}>{label}</Label>{multiline?<Textarea id={path} className="mt-1 min-h-24" value={current} onChange={(e)=>onChange(setPath(config,path,e.target.value))}/>:<Input id={path} className="mt-1" value={current} onChange={(e)=>onChange(setPath(config,path,e.target.value))}/>} {limit?<p className="mt-1 text-right text-xs text-slate-400">{current.length}/{limit}</p>:null}</div>; }

export function SiteProposalConfigEditor({ config, onChange }: { config: SiteConfig; onChange: (next: SiteConfig) => void }) {
  const [json,setJson]=useState(()=>JSON.stringify(config,null,2));const [error,setError]=useState<string|null>(null);useEffect(()=>setJson(JSON.stringify(config,null,2)),[config]);
  const version=String((config.template as JsonObject).templateVersion||"");const v2=version==="2.0.0";const content=config.content as JsonObject;
  const services=(v2?content.services:((content.treatments as JsonObject)?.cards||[])) as JsonObject[];const images=config.images||{};
  const changeImage=(slot:string,next:SiteConfig)=>onChange(v2?setPath(next,`images.${slot}.sourceMethod`,"manual"):next);
  const apply=()=>{try{const parsed=JSON.parse(json) as SiteConfig;if(hasUnsafePrototype(parsed))throw new Error("Chiavi non consentite");onChange(parsed);setError(null);toast.success("JSON applicato al draft.");}catch(e){setError(e instanceof Error?e.message:"JSON non valido");}};
  return <div className="space-y-5">
    <CommercialSectionCard title="Identità"><div className="grid gap-4 md:grid-cols-2"><Field config={config} path="brand.name" label="Nome" onChange={onChange}/><Field config={config} path="brand.descriptor" label="Categoria / descrittore" onChange={onChange}/><Field config={config} path="brand.professionalTitle" label="Qualifica" onChange={onChange}/><Field config={config} path="business.city" label="Città" onChange={onChange}/><div className="md:col-span-2"><Field config={config} path="sourceWebsite.url" label="Sito attuale" onChange={onChange}/></div></div></CommercialSectionCard>
    <CommercialSectionCard title="Brand"><div className="grid gap-4 lg:grid-cols-2"><Field config={config} path={v2?"images.logoDefault.src":"images.logo.src"} label="Logo default" onChange={onChange}/>{v2?<Field config={config} path="images.logoLight.src" label="Logo light" onChange={onChange}/>:null}<Field config={config} path="brand.logoMethod" label="Metodo rilevamento" onChange={onChange}/><div><Label>Palette principale</Label><div className="mt-2 flex flex-wrap gap-2">{Array.isArray(config.palette)?config.palette.slice(0,4).map((item)=><span key={item.variable} className="rounded-lg border px-2 py-1 text-xs"><i className="mr-2 inline-block h-3 w-3 rounded-full" style={{background:item.value}}/>{item.variable}</span>):Object.entries(config.palette).slice(0,4).map(([key,color])=><span key={key} className="rounded-lg border px-2 py-1 text-xs"><i className="mr-2 inline-block h-3 w-3 rounded-full" style={{background:String(color)}}/>{key}</span>)}</div></div></div>{Array.isArray((config.brand as JsonObject).warnings)&&((config.brand as JsonObject).warnings as unknown[]).length?<p className="mt-4 text-sm text-amber-700">{((config.brand as JsonObject).warnings as unknown[]).join(" · ")}</p>:null}</CommercialSectionCard>
    <CommercialSectionCard title="Servizi"><div className="grid gap-4 lg:grid-cols-3">{services.slice(0,3).map((service,index)=><div key={index} className="space-y-3 rounded-xl border p-4"><Field config={config} path={v2?`content.services.${index}.title`:`content.treatments.cards.${index}.title`} label={`Servizio ${index+1}`} onChange={onChange}/><Field config={config} path={v2?`content.services.${index}.description`:`content.treatments.cards.${index}.description`} label="Descrizione" multiline onChange={onChange}/></div>)}</div></CommercialSectionCard>
    <CommercialSectionCard title="Immagini"><div className="grid gap-4 lg:grid-cols-3">{Object.entries(images).filter(([slot])=>v2?["hero","consultation","feature"].includes(slot):["hero","consultation","products"].includes(slot)).map(([slot,image])=><div key={slot} className="rounded-xl border p-4">{image.src?<img src={String(image.src)} alt={String(image.alt||slot)} className="mb-3 h-36 w-full rounded-lg object-cover"/>:null}<Field config={config} path={`images.${slot}.src`} label={slot} onChange={(next)=>changeImage(slot,next)}/><Field config={config} path={`images.${slot}.alt`} label="Testo alternativo" onChange={onChange}/><p className="mt-2 text-xs text-slate-500">Metodo: {String(image.sourceMethod||((config.personalization as JsonObject)?.assetMethod)||"manual")}</p></div>)}</div></CommercialSectionCard>
    <CommercialSectionCard title="Contenuti principali"><div className="grid gap-4 lg:grid-cols-2"><Field config={config} path={v2?"content.hero.title":"content.hero.titleLine"} label="Titolo hero" onChange={onChange}/><Field config={config} path="content.hero.description" label="Descrizione hero" multiline onChange={onChange}/>{v2?<><Field config={config} path="content.approach.title" label="Titolo approccio" onChange={onChange}/><Field config={config} path="content.approach.description" label="Approccio" multiline onChange={onChange}/><Field config={config} path="content.hero.primaryCta" label="CTA primaria" onChange={onChange}/><Field config={config} path="content.hero.secondaryCta" label="CTA secondaria" onChange={onChange}/></>:null}</div></CommercialSectionCard>
    <Collapsible><CommercialSectionCard title="Impostazioni avanzate"><CollapsibleTrigger asChild><Button variant="outline"><Settings2 className="mr-2 h-4 w-4"/>Apri SEO, routing, palette, trust, FAQ e JSON</Button></CollapsibleTrigger><CollapsibleContent className="mt-4 space-y-3"><Textarea value={json} onChange={(e)=>setJson(e.target.value)} className="min-h-[520px] font-mono text-xs" aria-label="Configurazione JSON avanzata"/>{error?<p className="text-sm text-rose-600">{error}</p>:null}<div className="flex gap-2"><Button variant="outline" onClick={()=>navigator.clipboard.writeText(json).then(()=>toast.success("SiteConfig copiato.")).catch(()=>toast.error("Copia non disponibile."))}><Clipboard className="mr-2 h-4 w-4"/>Copia</Button><Button onClick={apply}>Applica JSON al draft</Button></div></CollapsibleContent></CommercialSectionCard></Collapsible>
  </div>;
}
