"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { Archive, ChevronLeft, Download, Loader2, Save, Sparkles, Trash2, WandSparkles } from "lucide-react";
import { toast } from "sonner";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { CommercialEmptyState } from "@/components/tenant-commercial/commercial-ui";
import { useTenantAccess } from "@/contexts/TenantAccessContext";
import { archiveSiteProposal, deleteSiteProposal, downloadSiteProposalHtml, downloadSiteProposalZip, generateSiteProposal, getSiteProposal, listSiteProposalGenerations, listSiteProposalVersions, personalizeSiteProposal, updateSiteProposal, upgradeSiteProposalTemplate, type CommercialAnalysis, type SiteConfig, type SiteProposalDetail as DetailResponse, type SiteProposalGeneration, type SiteProposalVersion } from "@/lib/tenant-site-proposals-api";
import { copyJson, downloadBlob, formatDate, getErrorMessage, hasPermanentProposalDeleteRole, proposalStatusLabel } from "./site-proposal-utils";
import { SiteProposalConfigEditor } from "./site-proposal-config-editor";
import { SiteProposalCrmEditor } from "./site-proposal-crm-editor";
import { SiteProposalEmailAnalysis } from "./site-proposal-email-analysis";
import { SiteProposalFilesPanel } from "./site-proposal-files-panel";
import { SiteProposalActivityPanel } from "./site-proposal-activity-panel";
import { SiteProposalPreview } from "./site-proposal-preview";
import { SiteProposalPersonalizationStatus } from "./site-proposal-personalization-status";

type Draft={displayName:string;siteConfig:SiteConfig;commercialAnalysis:CommercialAnalysis;emailSubject:string;emailBody:string;companyId?:string|null;contactId?:string|null;leadId?:string|null;opportunityId?:string|null};
const tabs=["dati","sito","contatti","email","file","attivita"] as const;type Tab=typeof tabs[number];
const makeDraft=(detail:DetailResponse):Draft=>{const p=detail.proposal;return {displayName:p.display_name,siteConfig:copyJson(p.site_config as SiteConfig),commercialAnalysis:copyJson(p.commercial_analysis||{}),emailSubject:p.email_subject||"",emailBody:p.email_body||"",companyId:p.company_id,contactId:p.contact_id,leadId:p.lead_id,opportunityId:p.opportunity_id}};

export function SiteProposalDetail({id}:{id:string}){
  const {canDelete,canManage,canUpdate}=useTenantAccess();const router=useRouter(),pathname=usePathname(),searchParams=useSearchParams();const query=searchParams.get("tab");const activeTab:Tab=tabs.includes(query as Tab)?query as Tab:"dati";
  const [detail,setDetail]=useState<DetailResponse|null>(null),[draft,setDraft]=useState<Draft|null>(null),[versions,setVersions]=useState<SiteProposalVersion[]>([]),[generations,setGenerations]=useState<SiteProposalGeneration[]>([]);const [loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[dirty,setDirty]=useState(false),[saving,setSaving]=useState(false),[generating,setGenerating]=useState(false),[personalizing,setPersonalizing]=useState(false),[deleting,setDeleting]=useState(false);const [archiveOpen,setArchiveOpen]=useState(false),[deleteOpen,setDeleteOpen]=useState(false),[personalizeOpen,setPersonalizeOpen]=useState(false),[upgradeOpen,setUpgradeOpen]=useState(false),[upgrading,setUpgrading]=useState(false);
  const load=useCallback(async()=>{setLoading(true);setError(null);try{const [d,v,g]=await Promise.all([getSiteProposal(id),listSiteProposalVersions(id),listSiteProposalGenerations(id)]);setDetail(d);setDraft(makeDraft(d));setVersions(v);setGenerations(g);setDirty(false)}catch(e){setError(getErrorMessage(e))}finally{setLoading(false)}},[id]);useEffect(()=>{void load()},[load]);useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue=""}};window.addEventListener("beforeunload",warn);return()=>window.removeEventListener("beforeunload",warn)},[dirty]);
  const changeTab=(tab:string)=>{const p=new URLSearchParams(searchParams.toString());p.set("tab",tab);router.replace(`${pathname}?${p}`,{scroll:false})};const updateDraft=(next:Draft)=>{setDraft(next);setDirty(true)};
  const save=useCallback(async()=>{if(!draft)return false;setSaving(true);try{await updateSiteProposal(id,{displayName:draft.displayName,siteConfig:draft.siteConfig,commercialAnalysis:draft.commercialAnalysis,emailSubject:draft.emailSubject,emailBody:draft.emailBody,companyId:draft.companyId||null,contactId:draft.contactId||null,leadId:draft.leadId||null,opportunityId:draft.opportunityId||null});toast.success("Proposta salvata.");await load();return true}catch(e){toast.error(getErrorMessage(e));return false}finally{setSaving(false)}},[draft,id,load]);
  const generate=useCallback(async(saveFirst=false)=>{if(dirty&&!saveFirst){toast.error("Sono presenti modifiche non salvate. Usa Salva e genera.");return}if(saveFirst&&!(await save()))return;setGenerating(true);try{await generateSiteProposal(id);toast.success("Proposta generata.");await load();changeTab("sito")}catch(e){toast.error(getErrorMessage(e))}finally{setGenerating(false)}},[dirty,id,load,save]);
  const personalize=async()=>{if(!detail)return;setPersonalizing(true);try{const legacy=detail.proposal.template_version!=="2.0.0";const result=await personalizeSiteProposal(id,Boolean(detail.proposal.latest_personalization_id),legacy);if(result.status==="fallback")toast.info("Personalizzazione locale applicata. Gemini non era disponibile.");else toast.success("Proposta analizzata e personalizzata.");setPersonalizeOpen(false);await load();changeTab("email")}catch(e){toast.error(getErrorMessage(e))}finally{setPersonalizing(false)}};
  const upgrade=async()=>{setUpgrading(true);try{await upgradeSiteProposalTemplate(id,"2.0.0");toast.success("Tema Colsova 2.0 applicato.");setUpgradeOpen(false);await load()}catch(e){toast.error(getErrorMessage(e))}finally{setUpgrading(false)}};
  const completed=useMemo(()=>generations.find(x=>x.status==="completed"),[generations]);const previewId=searchParams.get("generationId")||completed?.id;const busy=saving||generating||personalizing||upgrading;
  const download=async(kind:"html"|"zip")=>{if(!completed)return;try{const result=kind==="html"?await downloadSiteProposalHtml(id,completed.id):await downloadSiteProposalZip(id,completed.id);downloadBlob(result.blob,result.filename);toast.success("Download avviato.")}catch(e){toast.error(getErrorMessage(e))}};
  if(loading)return <main className="space-y-4 px-4 py-6 sm:px-6 lg:px-8"><Skeleton className="h-10 w-72"/><Skeleton className="h-[500px] w-full"/></main>;if(!detail||!draft)return <main className="px-4 py-6 sm:px-6 lg:px-8"><CommercialEmptyState>{error||"Proposta non trovata."}</CommercialEmptyState></main>;
  const proposal=detail.proposal,legacy=proposal.template_version!=="2.0.0";
  return <main className="space-y-5 px-4 py-6 sm:px-6 lg:px-8"><Link href="/commercial/site-proposals" className="inline-flex items-center gap-1 text-sm font-medium text-indigo-600"><ChevronLeft className="h-4 w-4"/>Proposte web</Link>
    <header className="flex flex-col gap-4 xl:flex-row xl:items-start xl:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h1 className="text-[30px] font-bold leading-tight text-slate-950">{draft.displayName}</h1><Badge>{proposalStatusLabel[proposal.status]||proposal.status}</Badge><SiteProposalPersonalizationStatus status={personalizing?"running":proposal.personalization_status}/>{dirty?<Badge className="bg-amber-100 text-amber-700">Modifiche non salvate</Badge>:null}</div><p className="mt-2 text-sm text-slate-500">Tema Colsova {proposal.template_version.startsWith("2")?"2.0":"1.0"} · configurazione v{proposal.current_version} · ultima generazione {formatDate(proposal.last_generated_at)}</p>{legacy?<button type="button" onClick={()=>setUpgradeOpen(true)} className="mt-2 text-sm font-semibold text-indigo-600 hover:underline">Nuovo Tema Colsova 2.0 disponibile · Visualizza novità</button>:null}</div>
    <div className="flex flex-wrap gap-2">{canManage("crm")?<Button disabled={busy||dirty} onClick={()=>setPersonalizeOpen(true)}>{personalizing?<Loader2 className="mr-2 h-4 w-4 animate-spin"/>:<WandSparkles className="mr-2 h-4 w-4"/>}{proposal.latest_personalization_id?"Rianalizza":"Analizza e personalizza"}</Button>:null}{canUpdate("crm")?<Button variant="outline" disabled={busy||!dirty} onClick={()=>void save()}><Save className="mr-2 h-4 w-4"/>Salva</Button>:null}{canManage("crm")?<Button disabled={busy||!dirty} onClick={()=>void generate(true)}><Sparkles className="mr-2 h-4 w-4"/>Salva e genera</Button>:null}{canManage("crm")?<Button variant="outline" disabled={busy} onClick={()=>void generate()}><Sparkles className="mr-2 h-4 w-4"/>Genera</Button>:null}<Button variant="outline" disabled={!completed||busy} onClick={()=>void download("html")}><Download className="mr-2 h-4 w-4"/>HTML</Button><Button variant="outline" disabled={!completed||busy} onClick={()=>void download("zip")}><Download className="mr-2 h-4 w-4"/>ZIP</Button>{canDelete("crm")?<Button variant="outline" disabled={busy} onClick={()=>setArchiveOpen(true)}><Archive className="mr-2 h-4 w-4"/>Archivia</Button>:null}{canDelete("crm")&&hasPermanentProposalDeleteRole()?<Button variant="destructive" disabled={busy||deleting} onClick={()=>setDeleteOpen(true)}><Trash2 className="mr-2 h-4 w-4"/>Elimina</Button>:null}</div></header>
    <Tabs value={activeTab} onValueChange={changeTab}><TabsList className="h-auto w-full justify-start overflow-x-auto"><TabsTrigger value="dati">Dati</TabsTrigger><TabsTrigger value="sito">Sito</TabsTrigger><TabsTrigger value="contatti">Contatti</TabsTrigger><TabsTrigger value="email">Email</TabsTrigger><TabsTrigger value="file">File</TabsTrigger><TabsTrigger value="attivita">Attività</TabsTrigger></TabsList></Tabs>
    {activeTab==="dati"?<SiteProposalConfigEditor config={draft.siteConfig} onChange={siteConfig=>updateDraft({...draft,siteConfig})}/>:null}{activeTab==="sito"?<SiteProposalPreview id={id} generationId={previewId} onGenerate={()=>void generate(false)}/>:null}{activeTab==="contatti"?<SiteProposalCrmEditor config={draft.siteConfig} links={draft} onConfigChange={siteConfig=>updateDraft({...draft,siteConfig})} onLinksChange={links=>updateDraft({...draft,...links})}/>:null}{activeTab==="email"?<SiteProposalEmailAnalysis analysis={draft.commercialAnalysis} status={proposal.personalization_status} subject={draft.emailSubject} body={draft.emailBody} originalSubject={proposal.email_subject||""} originalBody={proposal.email_body||""} onAnalysisChange={commercialAnalysis=>updateDraft({...draft,commercialAnalysis})} onEmailChange={({subject,emailBody:ignored,body}:{subject:string;emailBody?:string;body:string})=>{void ignored;updateDraft({...draft,emailSubject:subject,emailBody:body})}}/>:null}{activeTab==="file"?<SiteProposalFilesPanel proposalId={id} generations={generations} versions={versions} onPreview={generationId=>{const p=new URLSearchParams(searchParams.toString());p.set("tab","sito");p.set("generationId",generationId);router.replace(`${pathname}?${p}`,{scroll:false})}} onRestore={load}/>:null}{activeTab==="attivita"?<SiteProposalActivityPanel proposalId={id}/>:null}
    <AlertDialog open={personalizeOpen} onOpenChange={setPersonalizeOpen}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{proposal.latest_personalization_id?"Rianalizza proposta":"Analizza e personalizza"}</AlertDialogTitle><AlertDialogDescription>{legacy?"La proposta sarà prima aggiornata al Tema Colsova 2.0 e poi personalizzata. Il sito pubblico verrà analizzato; se Gemini non è disponibile sarà applicato il motore locale.":"Il sito pubblico verrà analizzato per logo, palette, social, immagini, copy, analisi commerciale ed email. Se Gemini non è disponibile sarà applicato il motore locale."}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Annulla</AlertDialogCancel><AlertDialogAction disabled={personalizing} onClick={()=>void personalize()}>{legacy?"Aggiorna e personalizza":"Analizza e personalizza"}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
    <AlertDialog open={upgradeOpen} onOpenChange={setUpgradeOpen}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Nuovo Tema Colsova 2.0 disponibile</AlertDialogTitle><AlertDialogDescription>La nuova versione introduce header sticky, doppio logo, social, immagini reali, copy differenziato, punti di fiducia e personalizzazione AI opzionale. Le generazioni precedenti restano disponibili e non verrà generato automaticamente nuovo HTML.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Annulla</AlertDialogCancel><AlertDialogAction disabled={upgrading} onClick={()=>void upgrade()}>Aggiorna tema</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
    <AlertDialog open={archiveOpen} onOpenChange={setArchiveOpen}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Archivia proposta</AlertDialogTitle><AlertDialogDescription>“{proposal.display_name}” verrà spostata nell’Archivio e potrà essere ripristinata.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Annulla</AlertDialogCancel><AlertDialogAction onClick={()=>archiveSiteProposal(id).then(()=>{toast.success("Proposta archiviata.");router.push("/commercial/site-proposals")}).catch(e=>toast.error(getErrorMessage(e)))}>Archivia</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
    <AlertDialog open={deleteOpen} onOpenChange={setDeleteOpen}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Elimina definitivamente la proposta</AlertDialogTitle><AlertDialogDescription>La proposta “{proposal.display_name}”, tutte le versioni, le generazioni e i relativi file HTML e ZIP verranno eliminati definitivamente. L’operazione non può essere annullata.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Annulla</AlertDialogCancel><AlertDialogAction className="bg-destructive text-destructive-foreground hover:bg-destructive/90" disabled={deleting} onClick={()=>{setDeleting(true);deleteSiteProposal(id).then(()=>{toast.success("Proposta eliminata definitivamente.");router.push("/commercial/site-proposals")}).catch(e=>toast.error(getErrorMessage(e))).finally(()=>setDeleting(false))}}>Elimina definitivamente</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </main>;
}
