"use client";

import { ArrowDown, ArrowUp, Plus, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { Textarea } from "@/components/ui/textarea";
import { CommercialSectionCard } from "@/components/tenant-commercial/commercial-ui";
import type { CommercialAnalysis, JsonObject } from "@/lib/tenant-site-proposals-api";
import { copyJson } from "./site-proposal-utils";

function StringList({ title, items, onChange }: { title: string; items: string[]; onChange: (items: string[]) => void }) { const update = (index: number, value: string) => { const next = [...items]; next[index] = value; onChange(next); }; return <div className="rounded-xl border border-slate-200 p-4"><div className="flex items-center justify-between gap-3"><h3 className="font-semibold text-slate-900">{title}</h3><Button type="button" size="sm" variant="outline" onClick={() => onChange([...items, "Nuovo elemento"])}><Plus className="mr-1 h-3.5 w-3.5" />Aggiungi</Button></div><div className="mt-3 space-y-2">{items.map((item, index) => <div key={`${index}-${item}`} className="flex gap-2"><Input value={item} onChange={(event) => update(index, event.target.value)} /><Button type="button" size="icon" variant="ghost" aria-label="Sposta su" disabled={index === 0} onClick={() => { const next = [...items]; [next[index - 1], next[index]] = [next[index], next[index - 1]]; onChange(next); }}><ArrowUp className="h-4 w-4" /></Button><Button type="button" size="icon" variant="ghost" aria-label="Sposta giù" disabled={index === items.length - 1} onClick={() => { const next = [...items]; [next[index + 1], next[index]] = [next[index], next[index + 1]]; onChange(next); }}><ArrowDown className="h-4 w-4" /></Button><Button type="button" size="icon" variant="ghost" aria-label="Rimuovi" onClick={() => onChange(items.filter((_, itemIndex) => itemIndex !== index))}><Trash2 className="h-4 w-4" /></Button></div>)}</div></div>; }
function ObjectList({ title, items, verified, onChange }: { title: string; items: JsonObject[]; verified?: boolean; onChange: (items: JsonObject[]) => void }) { const update = (index: number, key: string, value: string | boolean) => { const next = copyJson(items); next[index] = { ...next[index], [key]: value }; onChange(next); }; return <div className="rounded-xl border border-slate-200 p-4"><h3 className="font-semibold text-slate-900">{title}</h3><div className="mt-3 space-y-3">{items.map((item, index) => <div key={index} className="rounded-lg bg-slate-50 p-3"><div className="flex gap-2"><Input value={String(item.label || "")} onChange={(event) => update(index, "label", event.target.value)} placeholder="Titolo" /><Button type="button" size="icon" variant="ghost" aria-label="Rimuovi" onClick={() => onChange(items.filter((_, itemIndex) => itemIndex !== index))}><Trash2 className="h-4 w-4" /></Button></div><Textarea className="mt-2" value={String(item.note || item.description || "")} onChange={(event) => update(index, "note", event.target.value)} placeholder="Nota" />{verified ? <p className={`mt-2 text-xs ${item.verified === false ? "text-amber-700" : "text-emerald-700"}`}>{item.verified === false ? "Osservazione da verificare" : "Fatto disponibile"}</p> : null}</div>)}</div><Button type="button" size="sm" variant="outline" className="mt-3" onClick={() => onChange([...items, { label: "Nuovo elemento", verified: false }])}><Plus className="mr-1 h-3.5 w-3.5" />Aggiungi</Button></div>; }

export function SiteProposalAnalysisEditor({ analysis, onChange }: { analysis: CommercialAnalysis; onChange: (next: CommercialAnalysis) => void }) { const set = (key: string, value: unknown) => onChange({ ...analysis, [key]: value }); return <div className="space-y-5"><CommercialSectionCard title="Analisi commerciale"><div className="grid gap-4 md:grid-cols-2"><div><Label>Mode</Label><Input className="mt-1" readOnly value={String(analysis.mode || "—")} /></div><div><Label>Status</Label><Input className="mt-1" value={String(analysis.status || "")} onChange={(event) => set("status", event.target.value)} /></div><div className="flex items-center gap-3"><Switch id="manual-review" checked={Boolean(analysis.requiresManualReview)} onCheckedChange={(checked) => set("requiresManualReview", checked)} /><Label htmlFor="manual-review">Richiede revisione manuale</Label></div></div></CommercialSectionCard><ObjectList title="Punti di forza" items={(analysis.strengths || []) as JsonObject[]} verified onChange={(items) => set("strengths", items)} /><ObjectList title="Aree di miglioramento" items={(analysis.improvementAreas || []) as JsonObject[]} verified onChange={(items) => set("improvementAreas", items)} /><div className="grid gap-5 lg:grid-cols-2"><StringList title="Benefici" items={analysis.benefits || []} onChange={(items) => set("benefits", items)} /><StringList title="Esperienza desktop" items={analysis.desktopExperience || []} onChange={(items) => set("desktopExperience", items)} /><StringList title="Esperienza mobile-first" items={analysis.mobileFirstExperience || []} onChange={(items) => set("mobileFirstExperience", items)} /><StringList title="Motivazioni" items={analysis.rationale || []} onChange={(items) => set("rationale", items)} /></div><ObjectList title="Evidenze" items={(analysis.evidence || []) as JsonObject[]} verified onChange={(items) => set("evidence", items)} /></div>; }
