"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { CheckCircle2, ChevronLeft, CircleAlert, Loader2, Sparkles } from "lucide-react";
import { toast } from "sonner";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { CommercialEmptyState, CommercialKpiCard, CommercialPageHeader, CommercialSectionCard } from "@/components/tenant-commercial/commercial-ui";
import { useTenantAccess } from "@/contexts/TenantAccessContext";
import { confirmImport, generateImportBatch, getImportBatch, listSiteProposals, type SiteProposal, type SiteProposalImportBatch } from "@/lib/tenant-site-proposals-api";
import { formatDate, getErrorMessage, importStatusLabel, shortHash } from "./site-proposal-utils";

export function SiteProposalImportDetail({ id }: { id: string }) {
  const { canCreate, canManage } = useTenantAccess(); const [batch, setBatch] = useState<SiteProposalImportBatch | null>(null); const [proposals, setProposals] = useState<SiteProposal[]>([]); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [confirmOpen, setConfirmOpen] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(null); try { const current = await getImportBatch(id); setBatch(current); if (["confirmed", "generated", "partial"].includes(current.status)) { const result = await listSiteProposals({ importBatchId: id, limit: 100 }); setProposals(result.items); } } catch (value) { setError(getErrorMessage(value)); } finally { setLoading(false); } }, [id]);
  useEffect(() => { void load(); }, [load]);
  const confirm = async () => { setBusy(true); try { const result = await confirmImport(id); setProposals(result.proposals || []); toast.success(result.idempotent ? "Import già confermato." : "Import confermato."); setConfirmOpen(false); await load(); } catch (value) { toast.error(getErrorMessage(value)); } finally { setBusy(false); } };
  const generate = async () => { setBusy(true); try { const result = await generateImportBatch(id); toast.success(`Generazione completata: ${result.success} riuscite, ${result.failed} errori.`); await load(); } catch (value) { toast.error(getErrorMessage(value)); } finally { setBusy(false); } };
  if (loading) return <main className="space-y-4 px-4 py-6 sm:px-6 lg:px-8"><Skeleton className="h-10 w-80" /><Skeleton className="h-64 w-full" /></main>;
  if (!batch) return <main className="px-4 py-6 sm:px-6 lg:px-8"><CommercialEmptyState>{error || "Import non trovato."}</CommercialEmptyState></main>;
  const warnings = batch.rows.reduce((sum, row) => sum + row.warnings.length, 0);
  return <main className="space-y-5 px-4 py-6 sm:px-6 lg:px-8"><Link href="/commercial/site-proposals/new" className="inline-flex items-center gap-1 text-sm font-medium text-indigo-600"><ChevronLeft className="h-4 w-4" />Nuovo import</Link><CommercialPageHeader title={batch.original_filename} description={`Template ${batch.template_slug} · ${formatDate(batch.created_at)} · hash ${shortHash(batch.source_sha256)}`} />
    <div className="flex flex-wrap items-center gap-3"><Badge>{importStatusLabel[batch.status] || batch.status}</Badge><span className="text-sm text-slate-500">{batch.row_count} righe · {batch.valid_count} valide · {batch.invalid_count} non valide</span>{batch.status === "preview" && canCreate("crm") ? <Button disabled={busy} onClick={() => setConfirmOpen(true)}><CheckCircle2 className="mr-2 h-4 w-4" />Conferma importazione</Button> : null}{batch.status === "confirmed" && canManage("crm") ? <Button disabled={busy} onClick={() => void generate()}>{busy ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Sparkles className="mr-2 h-4 w-4" />}Genera tutte le proposte</Button> : null}</div>
    {error ? <p className="rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">{error}</p> : null}<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><CommercialKpiCard label="Righe totali" value={batch.row_count} icon={CircleAlert} tone="violet" /><CommercialKpiCard label="Valide" value={batch.valid_count} icon={CheckCircle2} tone="green" /><CommercialKpiCard label="Con errori" value={batch.invalid_count} icon={CircleAlert} tone="orange" /><CommercialKpiCard label="Warning" value={warnings} icon={CircleAlert} tone="blue" /></div>
    <CommercialSectionCard title="Anteprima righe">{batch.rows.length === 0 ? <CommercialEmptyState>Nessuna riga disponibile.</CommercialEmptyState> : <div className="space-y-2">{batch.rows.map((row) => <details key={row.rowIndex} className="rounded-xl border border-slate-200 bg-white"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 px-4 py-3"><span className="min-w-0"><strong className="text-sm text-slate-900">#{row.rowIndex} {row.displayName || "Riga senza nome"}</strong><span className="ml-2 text-xs text-slate-500">{String(row.canonical?.city || "—")}</span></span><Badge className={row.valid ? "bg-emerald-100 text-emerald-700" : "bg-rose-100 text-rose-700"}>{row.valid ? "Valida" : "Non valida"}</Badge></summary><div className="grid gap-4 border-t px-4 py-4 text-sm md:grid-cols-2"><div><h3 className="font-medium text-slate-900">Dati canonici</h3><dl className="mt-2 space-y-1 text-slate-600"><div>Attività: {String(row.canonical?.businessName || "—")}</div><div>Città: {String(row.canonical?.city || "—")}</div><div>Sito: {String(row.canonical?.websiteUrl || "—")}</div><div>Servizi: {Array.isArray(row.canonical?.services) ? row.canonical?.services.join(", ") : "—"}</div></dl></div><div><h3 className="font-medium text-slate-900">Esito</h3>{row.errors.concat(row.warnings).length ? <ul className="mt-2 space-y-1 text-slate-600">{row.errors.concat(row.warnings).map((issue, index) => <li key={`${issue.code}-${index}`}>{issue.message}</li>)}</ul> : <p className="mt-2 text-slate-600">Nessun errore o warning.</p>}</div>{row.siteConfig ? <p className="md:col-span-2 text-xs text-slate-500">SiteConfig pronto: 3 trattamenti, 3 punti prodotto, 6 recensioni e 6 FAQ.</p> : null}</div></details>)}</div>}</CommercialSectionCard>
    {proposals.length ? <CommercialSectionCard title="Proposte create"><div className="flex flex-wrap gap-2">{proposals.map((proposal) => <Button key={proposal.id} variant="outline" asChild><Link href={`/commercial/site-proposals/${proposal.id}`}>{proposal.display_name}</Link></Button>)}</div></CommercialSectionCard> : null}
    <AlertDialog open={confirmOpen} onOpenChange={setConfirmOpen}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Conferma importazione</AlertDialogTitle><AlertDialogDescription>Le righe valide creeranno proposte in bozza. L’operazione è idempotente.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Annulla</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={() => void confirm()}>Conferma importazione</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </main>;
}
