"use client";

import { Badge } from "@/components/ui/badge";
import { CommercialSectionCard } from "@/components/tenant-commercial/commercial-ui";
import type { CommercialAnalysis, JsonObject, PersonalizationStatus } from "@/lib/tenant-site-proposals-api";
import { SiteProposalAnalysisEditor } from "./site-proposal-analysis-editor";
import { SiteProposalEmailEditor } from "./site-proposal-email-editor";

function List({title,items}:{title:string;items:unknown[]}){return <div><h3 className="text-sm font-semibold text-slate-900">{title}</h3><ul className="mt-2 space-y-2 text-sm text-slate-600">{items.length?items.map((item,index)=><li key={index} className="rounded-lg bg-slate-50 p-3">{typeof item==="string"?item:String((item as JsonObject).label||(item as JsonObject).evidence||(item as JsonObject).businessImpact||"Elemento da verificare")}</li>):<li className="text-slate-400">Nessun elemento disponibile.</li>}</ul></div>}
export function SiteProposalEmailAnalysis({analysis,status,subject,body,originalSubject,originalBody,onAnalysisChange,onEmailChange}:{analysis:CommercialAnalysis;status?:PersonalizationStatus|null;subject:string;body:string;originalSubject:string;originalBody:string;onAnalysisChange:(next:CommercialAnalysis)=>void;onEmailChange:(next:{subject:string;body:string})=>void}){const local=status==="fallback";return <div className="space-y-5"><CommercialSectionCard title="Analisi del sito attuale"><div className="mb-4 flex flex-wrap gap-2">{status==="completed"?<Badge>AI Gemini</Badge>:null}{local?<Badge className="bg-indigo-100 text-indigo-700">Motore locale</Badge>:null}{analysis.requiresManualReview?<Badge className="bg-amber-100 text-amber-700">Da verificare</Badge>:null}</div><p className="text-sm leading-6 text-slate-700">{String(analysis.summary||"Analisi non ancora disponibile. Usa Analizza e personalizza.")}</p><div className="mt-5 grid gap-5 lg:grid-cols-2"><List title="Punti positivi" items={analysis.strengths||[]}/><List title="Aree migliorabili" items={analysis.improvementAreas||[]}/><List title="Opportunità" items={(analysis.opportunities as unknown[])||[]}/><List title="Perché doFlow" items={(analysis.whyDoflow as unknown[])||[]}/><List title="Evidenze" items={analysis.evidence||[]}/></div></CommercialSectionCard><SiteProposalEmailEditor subject={subject} body={body} originalSubject={originalSubject} originalBody={originalBody} onChange={onEmailChange}/><details className="rounded-xl border bg-white p-4"><summary className="cursor-pointer text-sm font-semibold">Modifica analisi strutturata</summary><div className="mt-4"><SiteProposalAnalysisEditor analysis={analysis} onChange={onAnalysisChange}/></div></details></div>}
