"use client"

import { useState } from "react"
import { Building2, CalendarClock, ChartPie, Check, ChevronDown, ChevronUp, Coins, FileText, MapPin, Pencil, Star } from "lucide-react"
import { toast } from "sonner"

import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "@/components/ui/collapsible"
import { Command, CommandEmpty, CommandGroup, CommandInput, CommandItem, CommandList } from "@/components/ui/command"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover"
import { Progress } from "@/components/ui/progress"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Separator } from "@/components/ui/separator"
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip"
import { LeadQuickActions } from "@/features/commercial/components/lead-detail/lead-detail-actions"
import { GuidedCallButton } from "@/features/commercial/components/guided-call-sheet"
import { useCommercialLeads } from "@/features/commercial/components/commercial-leads-provider"
import type { CommercialLead, PipelineStage, TeamMember } from "@/features/commercial/types"

type Stage = { id: PipelineStage; label: string }
type Props = { lead: CommercialLead; team: TeamMember[]; stages: Stage[]; onCreateActivity?: () => void }
const money = new Intl.NumberFormat("it-IT", { style: "currency", currency: "EUR", useGrouping: "always", maximumFractionDigits: 0 })
const submittedAt = new Intl.DateTimeFormat("it-IT", { day: "2-digit", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit" })
const serviceOptions = ["Sito web", "E-commerce", "Landing page", "Campagne", "Branding", "Automazioni", "Altro"]
const tone: Record<PipelineStage, string> = { new: "bg-chart-2/10 text-chart-2", qualified: "bg-chart-1/10 text-chart-1", proposal: "bg-chart-4/10 text-chart-4", negotiation: "bg-chart-5/10 text-chart-5", won: "bg-chart-3/10 text-chart-3", unqualified: "bg-muted text-muted-foreground", "not-interested": "bg-muted text-muted-foreground", "follow-up": "bg-chart-2/10 text-chart-2", lost: "bg-destructive/10 text-destructive" }
const mainStageLabels: Record<string, string> = { new: "Nuovo lead", qualified: "Qualificato", proposal: "Proposta inviata", negotiation: "Negoziazione", won: "Vinto" }

function RequestField({ label, children }: { label: string; children: React.ReactNode }) {
  return <div className="min-w-0"><p className="text-xs text-muted-foreground">{label}</p><div className="mt-1 text-sm font-medium">{children}</div></div>
}

export function LeadDetailOperationalCard({ lead, team, stages, onCreateActivity }: Props) {
  const commercialStore = useCommercialLeads()
  const initialServices = lead.services?.length ? Array.from(new Set(lead.services)) : lead.service ? [lead.service] : []
  const [stage, setStage] = useState(lead.stage)
  const [owner, setOwner] = useState(lead.assigneeId)
  const [services, setServices] = useState(initialServices)
  const [serviceDraft, setServiceDraft] = useState(initialServices)
  const [servicesOpen, setServicesOpen] = useState(false)
  const [originalRequestOpen, setOriginalRequestOpen] = useState(false)
  const [value, setValue] = useState(lead.value)
  const [probability, setProbability] = useState(lead.probability)
  const [valueDraft, setValueDraft] = useState(String(lead.value))
  const [probabilityDraft, setProbabilityDraft] = useState(String(lead.probability))
  const [valueOpen, setValueOpen] = useState(false)
  const [probabilityOpen, setProbabilityOpen] = useState(false)
  const [pendingStage, setPendingStage] = useState<PipelineStage | null>(null)
  const title = lead.opportunityName || lead.company || lead.firstName + " " + lead.lastName
  const province = lead.location ?? lead.originalRequest?.province ?? lead.formSubmission?.province ?? "—"
  const ownerName = team.find((member) => member.id === owner)?.name ?? "—"
  const weightedValue = value * probability / 100
  const request = lead.originalRequest
  const setCommercialStage = async (nextStage: PipelineStage) => { if (nextStage === "won" || nextStage === "lost") { setPendingStage(nextStage); return }; await commercialStore.transitionLeadStatus({ leadId: lead.id, fromStatus: lead.stage, toStatus: nextStage }); setStage(nextStage); toast.success("Stato aggiornato: " + (mainStageLabels[nextStage] ?? stages.find((item) => item.id === nextStage)?.label)); }
  const confirmStage = async () => { if (!pendingStage) return; try { await commercialStore.transitionLeadStatus({ leadId: lead.id, fromStatus: lead.stage, toStatus: pendingStage, options: { createOnboardingActivity: pendingStage === "won" } }); setStage(pendingStage); if (pendingStage === "won") setProbability(100); toast.success(pendingStage === "won" ? "Cliente creato correttamente" : "Stato aggiornato: " + (mainStageLabels[pendingStage] ?? stages.find((item) => item.id === pendingStage)?.label)); } catch { toast.error(pendingStage === "won" ? "Impossibile creare il cliente. Nessuna modifica è stata salvata." : "Impossibile aggiornare lo stato.") } finally { setPendingStage(null) } }
  const saveValue = () => { const nextValue = Number(valueDraft); if (!Number.isFinite(nextValue) || nextValue < 0) { toast.error("Inserisci un valore valido non negativo"); return }; commercialStore.updateLead(lead.id, { value: nextValue }); setValue(nextValue); setValueOpen(false); toast.success("Valore trattativa aggiornato") }
  const saveProbability = () => { const nextProbability = Number(probabilityDraft); if (!Number.isFinite(nextProbability) || nextProbability < 0 || nextProbability > 100) { toast.error("Inserisci una probabilità tra 0 e 100"); return }; commercialStore.updateLead(lead.id, { probability: nextProbability }); setProbability(nextProbability); setProbabilityOpen(false); toast.success("Probabilità aggiornata") }
  const toggleDraftService = (service: string) => setServiceDraft((current) => current.includes(service) ? current.filter((item) => item !== service) : [...current, service])
  const saveServices = () => { const nextServices = Array.from(new Set(serviceDraft)); commercialStore.updateLead(lead.id, { services: nextServices, service: nextServices[0] ?? lead.service }); setServices(nextServices); setServicesOpen(false); toast.success("Servizi aggiornati") }
  const cancelServices = () => { setServiceDraft(services); setServicesOpen(false) }

  return <><div className="grid items-start gap-4 xl:grid-cols-12"><Card data-flow-tour="flow-lead-overview" className="self-start rounded-xl shadow-none xl:col-span-9"><CardContent className="space-y-3 p-3 sm:p-4">
    <div className="flex flex-col gap-4 2xl:flex-row 2xl:items-start 2xl:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h1 className="text-lg font-semibold tracking-tight">{title}</h1><Button size="icon-sm" variant="ghost" aria-label="Aggiungi ai preferiti" onClick={() => toast.info("Preferiti disponibili nella prossima fase.")}><Star /></Button><Badge className={["border-0", tone[stage]].join(" ")}>{mainStageLabels[stage] ?? stages.find((item) => item.id === stage)?.label ?? stage}</Badge></div><p className="mt-1 text-[10px] text-muted-foreground">ID lead: {lead.id}</p><div className="mt-2 flex flex-wrap gap-x-3 gap-y-1 text-xs text-muted-foreground"><span>{lead.firstName} {lead.lastName}</span><span className="inline-flex items-center gap-1"><Building2 className="size-3.5" />{lead.company || "—"}</span><a className="hover:text-foreground" href={"mailto:" + lead.email}>{lead.email || "—"}</a><a className="hover:text-foreground" href={"tel:" + lead.phone}>{lead.phone || "—"}</a><span className="inline-flex items-center gap-1"><MapPin className="size-3.5" />{province}</span></div><Collapsible open={originalRequestOpen} onOpenChange={setOriginalRequestOpen} className="mt-2"><CollapsibleTrigger asChild><Button variant="link" size="sm" className="h-auto px-0 text-xs"><FileText className="size-3.5" />Visualizza richiesta originale{originalRequestOpen ? <ChevronUp className="size-3.5" /> : <ChevronDown className="size-3.5" />}</Button></CollapsibleTrigger></Collapsible></div><div className="flex flex-wrap justify-end gap-2"><GuidedCallButton lead={lead} /><div className="overflow-x-auto"><LeadQuickActions firstName={lead.firstName} phone={lead.phone} email={lead.email} onCreateActivity={onCreateActivity} /></div></div></div>
    <Separator />
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><div><div className="flex items-center gap-1"><p className="text-xs text-muted-foreground">Servizio</p><Popover open={servicesOpen} onOpenChange={(open) => { if (open) setServiceDraft(services); setServicesOpen(open) }}><Tooltip><TooltipTrigger asChild><PopoverTrigger asChild><Button variant="ghost" size="icon-sm" aria-label="Modifica servizi"><Pencil className="size-3.5" /></Button></PopoverTrigger></TooltipTrigger><TooltipContent>Modifica servizi</TooltipContent></Tooltip><PopoverContent align="start" className="w-80"><Command><CommandInput placeholder="Cerca un servizio" /><CommandList><CommandEmpty>Nessun servizio trovato.</CommandEmpty><CommandGroup heading="Servizi disponibili">{serviceOptions.map((service) => <CommandItem key={service} value={service} onSelect={() => toggleDraftService(service)}><Check className={serviceDraft.includes(service) ? "size-4 opacity-100" : "size-4 opacity-0"} />{service}</CommandItem>)}</CommandGroup></CommandList></Command><div className="flex justify-end gap-2 border-t pt-2"><Button variant="outline" size="sm" onClick={cancelServices}>Annulla</Button><Button size="sm" onClick={saveServices}>Salva</Button></div></PopoverContent></Popover></div><div className="mt-1 flex flex-wrap gap-1">{services.length ? services.map((service) => <Badge key={service} variant="secondary">{service}</Badge>) : <span className="text-sm font-medium">—</span>}</div></div><div><p className="text-xs text-muted-foreground">Fonte</p><p className="mt-1 text-sm font-medium">{lead.source || "—"}</p></div>
    <div><p className="mb-1.5 text-xs text-muted-foreground">Stato</p><Select value={stage} onValueChange={(nextStage) => setCommercialStage(nextStage as PipelineStage)}><SelectTrigger className="h-9"><SelectValue /></SelectTrigger><SelectContent>{stages.map((item) => <SelectItem key={item.id} value={item.id}>{mainStageLabels[item.id] ?? item.label}</SelectItem>)}</SelectContent></Select></div><div><p className="mb-1.5 text-xs text-muted-foreground">Responsabile</p><Select value={owner} onValueChange={(nextOwner) => { setOwner(nextOwner); commercialStore.updateLead(lead.id, { assigneeId: nextOwner, owner: team.find((member) => member.id === nextOwner)?.name ?? lead.owner }); toast.success("Responsabile aggiornato") }}><SelectTrigger className="h-9"><SelectValue /></SelectTrigger><SelectContent>{team.map((member) => <SelectItem key={member.id} value={member.id}>{member.name}</SelectItem>)}</SelectContent></Select><p className="mt-1 text-xs text-muted-foreground">Assegnato a {ownerName}</p></div></div>
    <Collapsible open={originalRequestOpen} onOpenChange={setOriginalRequestOpen}><CollapsibleContent><Separator className="mb-4" />{!request ? <p className="text-sm text-muted-foreground">Nessuna richiesta originale disponibile</p> : <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><RequestField label="Progetto richiesto"><Badge className="bg-blue-500/10 text-blue-700 hover:bg-blue-500/10 dark:text-blue-300">{request.projectType}</Badge></RequestField><RequestField label="Obiettivi"><div className="flex flex-wrap gap-1">{request.objectives.slice(0, 2).map((objective) => <Badge key={objective} variant="secondary">{objective}</Badge>)}</div></RequestField><RequestField label="Tempistiche"><Badge className="bg-amber-500/10 text-amber-700 hover:bg-amber-500/10 dark:text-amber-300">{request.timing}</Badge></RequestField><RequestField label="Richiedente">{request.fullName}</RequestField><RequestField label="Azienda">{request.company || "—"}</RequestField><RequestField label="Email"><a className="break-all hover:text-foreground" href={"mailto:" + request.email}>{request.email}</a></RequestField><RequestField label="Telefono"><a className="hover:text-foreground" href={"tel:" + request.phone}>{request.phone}</a></RequestField><RequestField label="Provincia">{request.province}</RequestField><RequestField label="Provenienza">{request.source}</RequestField><RequestField label="URL pagina">{request.sourceUrl ? <a className="break-all hover:text-foreground" href={request.sourceUrl} target="_blank" rel="noreferrer">{request.sourceUrl}</a> : "—"}</RequestField><RequestField label="Data acquisizione">{submittedAt.format(new Date(request.submittedAt))}</RequestField></div>}</CollapsibleContent></Collapsible>
  </CardContent></Card>
  <aside className="grid items-start gap-2 sm:grid-cols-2 xl:col-span-3 xl:grid-cols-1"><Card className="gap-0 py-0"><CardContent className="p-3"><div className="flex items-start gap-2.5"><span className="grid size-8 shrink-0 place-items-center rounded-full bg-violet-500/10 text-violet-600"><Coins className="size-4" /></span><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><div><p className="text-xs text-muted-foreground">Valore trattativa</p><p className="text-lg font-semibold tabular-nums">{money.format(value)}</p></div><Tooltip><TooltipTrigger asChild><Button variant="ghost" size="icon-sm" aria-label="Modifica valore trattativa" onClick={() => { setValueDraft(String(value)); setValueOpen(true) }}><Pencil className="size-4" /></Button></TooltipTrigger><TooltipContent>Modifica valore trattativa</TooltipContent></Tooltip></div><p className="text-xs text-muted-foreground">{money.format(weightedValue)} valore ponderato</p></div></div></CardContent></Card>
  <Card className="gap-0 py-0"><CardContent className="p-3"><div className="flex items-start gap-2.5"><span className="grid size-8 shrink-0 place-items-center rounded-full bg-indigo-500/10 text-indigo-600"><ChartPie className="size-4" /></span><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><div><p className="text-xs text-muted-foreground">Probabilità di chiusura</p><p className="text-lg font-semibold tabular-nums">{probability}%</p></div><Tooltip><TooltipTrigger asChild><Button variant="ghost" size="icon-sm" aria-label="Modifica probabilità" onClick={() => { setProbabilityDraft(String(probability)); setProbabilityOpen(true) }}><Pencil className="size-4" /></Button></TooltipTrigger><TooltipContent>Modifica probabilità</TooltipContent></Tooltip></div><Progress className="mt-1.5 h-1 [&>div]:bg-indigo-500" value={probability} /><p className="mt-1.5 text-xs text-muted-foreground">{money.format(weightedValue)} valore ponderato</p></div></div></CardContent></Card>
  <Card data-flow-tour="flow-lead-next-action" className="gap-0 py-0"><CardContent className="p-3"><div className="flex items-start gap-2.5"><span className="grid size-8 shrink-0 place-items-center rounded-full bg-blue-500/10 text-blue-600"><CalendarClock className="size-4" /></span><div className="min-w-0 flex-1"><p className="text-xs text-muted-foreground">Prossima attività</p><p className="text-sm font-semibold">{lead.nextAction}</p><p className="mt-1 text-xs text-muted-foreground">{new Intl.DateTimeFormat("it-IT", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(lead.nextActionAt))}</p><Button variant="outline" size="sm" className="mt-2" onClick={() => toast.info("Dettaglio attività disponibile nella prossima fase.")}>Vai all’attività</Button></div></div></CardContent></Card></aside></div>
  <Dialog open={valueOpen} onOpenChange={setValueOpen}><DialogContent><DialogHeader><DialogTitle>Modifica valore trattativa</DialogTitle><DialogDescription>Aggiorna il valore economico della trattativa.</DialogDescription></DialogHeader><div className="grid gap-2"><Label htmlFor="deal-value">Valore in euro</Label><Input id="deal-value" type="number" min="0" step="1" value={valueDraft} onChange={(event) => setValueDraft(event.target.value)} /></div><DialogFooter><Button variant="outline" onClick={() => setValueOpen(false)}>Annulla</Button><Button onClick={saveValue}>Salva</Button></DialogFooter></DialogContent></Dialog>
  <Dialog open={probabilityOpen} onOpenChange={setProbabilityOpen}><DialogContent><DialogHeader><DialogTitle>Modifica probabilità di chiusura</DialogTitle><DialogDescription>Aggiorna la probabilità stimata per la trattativa.</DialogDescription></DialogHeader><div className="grid gap-2"><Label htmlFor="deal-probability">Probabilità</Label><Input id="deal-probability" type="number" min="0" max="100" step="1" value={probabilityDraft} onChange={(event) => setProbabilityDraft(event.target.value)} /></div><DialogFooter><Button variant="outline" onClick={() => setProbabilityOpen(false)}>Annulla</Button><Button onClick={saveProbability}>Salva</Button></DialogFooter></DialogContent></Dialog>
  <AlertDialog open={Boolean(pendingStage)} onOpenChange={(open) => !open && setPendingStage(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{pendingStage === "won" ? "Segnare l’opportunità come vinta?" : "Segnare l’opportunità come persa?"}</AlertDialogTitle><AlertDialogDescription>{pendingStage === "lost" ? "Potrai aggiungere la motivazione nella prossima fase." : "Lo stato commerciale verrà aggiornato localmente."}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Annulla</AlertDialogCancel><AlertDialogAction onClick={confirmStage}>Conferma</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </>
}
